### PR TITLE
Added one more question and answer

### PR DESCRIPTION
**Pull request by hivikash**
We can perform stylesheet linking  without {% load staticfiles %} tag

### CODE REVIEW

**Comment by PRMerger9** [comment]
@hivikash : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JoshuaPartlow** [comment]
Adding @Anapo14 to take a look. @Anapo14 - please work with @gregvanl to merge if it looks good.

**Comment by savannahostrowski** [comment]
Hey @hivikash!

Thanks for your contribution. After reviewing this, it looks sound. However, could you add a line that specifically calls out that what's happening is really just a substitution of  ../../ for {{ staticfiles }}?

Thanks!
Savannah

**Comment by ghogen** [comment]
@JoshuaPartlow Since there was no response from the OP, can you take action to close this?  Maybe submit a change internally and close this PR?

**Comment by JoshuaPartlow** [comment]
Yes, I'll accept this merge and add the note requested myself in a separate PR.

**Comment by JoshuaPartlow** [comment]
#sign-off

**Comment by ktoliver** [comment]
@hivikash - Thank you for your contribution. Would you take a moment to sign the CLA? After the CLA is signed, we can merge the PR. Thanks!

**Comment by ktoliver** [comment]
For PR review queue management, we'll add #hold-off. If the CLA is signed, the PR is ready to merge. Thanks.

**Pull request merged**
