### PR TITLE
Some improvement to completion for unimported items

### PR DESCRIPTION
**Pull request by genlu**
Addressing some of the issues in #5382, by adding info on:
1. completion for unimported extension methods
2. Expander button
3. Option that control this feature

I still believe this entry should be part of the IntelliSense instead of Refactoring, but fixing that would be a bigger change, so I will let @mikadumont handle it in the future. :)

### CODE REVIEW

**Comment by PRMerger13** [comment]
@genlu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @mikadumont and @genlu - New content should be merged in the private repo so it can be viewed on staging and benefit from automated validations, Acrolinx, and comprehensive PR review against the [PR review quality criteria](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master). I'll move this approved commit to the private repo and then sign off. I'll close this PR and post the new PR number shortly. Thanks.

**Comment by genlu** [comment]
@ktoliver Thanks! I was going to ask about how to validate some of the changes I made :)

**Comment by ktoliver** [comment]
@genlu The options in the public repo are relatively bare-bones; just GitHub Preview, which doesn't render all of the custom Markdown that's used in the content. The new PR in the private repo is https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6921. I made one change: removed "and" from the new article file name per the contributor guide. I signed off on the new PR. It will enter the private repo PR review queue. It should be reviewed within a couple hours. Thanks. We'll close this PR now.

**Pull request closed without merging**
