### PR TITLE
Added multi-level scanning/merging use case

### PR DESCRIPTION
**Pull request by grokky1**
Explanation of how to make msbuild scan and merge multiple levels of Directory.Build.props files, for more complex solution structures. Related to [2456](https://github.com/Microsoft/msbuild/issues/2456).

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/msbuild/customize-your-build.md](https://github.com/grokky1/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708230818517432-262%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/msbuild/customize-your-build.md](https://github.com/grokky1/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708231714141633-262%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by grokky1** [comment]
@msftclas I sent the CLA twice already please look into it.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/msbuild/customize-your-build.md](https://github.com/grokky1/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C30%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708302004334918-262%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by grokky1** [comment]
@Mikejo5000 There's a problem with the syntax, [see for more info](https://github.com/Microsoft/msbuild/issues/2456#issuecomment-324532209).

**Pull request merged**
