### PR TITLE
Update deprecated codeplex link to the latest github repo of MPF

### LINKED ISSUE #1027: The link of "Managed Package Framework for Projects" points to deprecated codeplex site
The link on this paragraph points to deprecated (for viewing only?) site:

> You can create your own project types with the Visual Studio SDK and the Managed Package Framework for Projects, which you can download at _Managed Package Framework for Projects_. 

Has the link been migrated to other OSS repo such as Github? Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e54b888-936c-aaff-c5f9-cd8d2324df39
* Version Independent ID: ad62b5a4-3198-b135-b7a1-9574cec41573
* Content: [Extending Projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-projects)
* Content Source: [docs/extensibility/extending-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extending-projects.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

### PR DESCRIPTION
**Pull request by eriawan**
This PR is to update deprecated codeplex link to the latest github repo of MPF.

Fixes #1027

### CODE REVIEW

**Comment by PRMerger8** [comment]
@eriawan : Thanks for your contribution! The author, @gregvanl, has been notified to review your proposed change.

**Comment by eriawan** [comment]
@gregvanl 

Please review.

**Comment by gregvanl** [comment]
Hi @eriawan Thanks for doing this. I see 6 other references to http://mpfproj12.codeplex.com under docs\extensibility. Would you like to update those as well in this PR?

**Comment by eriawan** [comment]
@gregvanl 

Thanks for the reply! Ok, I'm going to update the remaining references too in this PR.

**Comment by PRMerger15** [comment]
@eriawan : Thanks for your contribution! The author, @gregvanl, has been notified to review your proposed change.

**Comment by eriawan** [comment]
@gregvanl 

The remaining pages have been updated. Please review.
Thanks in advance! 🙂

**Comment by gregvanl** [comment]
#sign-off

**Comment by gewarren** [comment]
@eriawan Thanks so much for updating all the URLs.

**Comment by eriawan** [comment]
@gewarren 
you're welcome 🙂

**Pull request merged**
