### PR TITLE
Update C26400.md

### PR DESCRIPTION
**Pull request by seshenoy**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@seshenoy : Thanks for your contribution! The author, @mikeblome, has been notified to review your proposed change.

**Comment by seshenoy** [comment]
@mikeblome This is a test PR... please ignore the same. I will close this shortly.

**Comment by seshenoy** [comment]
#hold-off

**Comment by seshenoy** [comment]
#please-close

**Comment by seshenoy** [comment]
#hold-off

**Pull request closed without merging**
