### PR TITLE
Document where the VSIX theming tool tool can be found

### PR DESCRIPTION
**Pull request by Quenty**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Quenty : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by j-martens** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@j-martens: I'm sorry - only the author of this article, @acangialosi, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by j-martens** [comment]
@ktoliver @ghogen - can please help me get this merged?

**Pull request merged**
