### PR TITLE
initial control display options commit

### PR DESCRIPTION
**Pull request by diverdan92**
We are adding a new feature to change control display options. Adding docs for it.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@diverdan92 : Thanks for your contribution! The author, @gewarren, has been notified to review your proposed change.

**Comment by diverdan92** [comment]
@Genevieve Warren<mailto:Genevieve.Warren@microsoft.com> - let me know if you have any feedback or would like any changes or updates!

cc'ing the team that worked on this feature in case they also have feedback.
________________________________

**Comment by PRMerger20** [comment]
@diverdan92 : Thanks for your contribution! The author, @gewarren, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@diverdan92 This is awesome, thanks for adding! Can I ask you a big favor and move this PR to the private repo (visualstudio-docs-pr)? Microsoft authors are highly encouraged to use the private repo as it provides preview builds and other tools like Acrolinx checks. You'll need to associate your GitHub ID with your MS email address, and then join the Microsoft Docs organization.

**Pull request closed without merging**
