### PR TITLE
Update running-profiling-tools-with-or-without-the-debugger.md

### PR DESCRIPTION
**Pull request by linuxuser27**
Update wording regarding the expected precision/accuracy of the profiling tools during debugging.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/profiling/running-profiling-tools-with-or-without-the-debugger.md](https://github.com/linuxuser27/visualstudio-docs/blob/patch-1/docs/profiling/running-profiling-tools-with-or-without-the-debugger.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C1%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708011907574793-211%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AaronRobinsonMSFT** [comment]
This is a good change.

**Comment by Mikejo5000** [comment]
I'm checking with the profiling team on this change...

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/profiling/running-profiling-tools-with-or-without-the-debugger.md](https://github.com/linuxuser27/visualstudio-docs/blob/patch-1/docs/profiling/running-profiling-tools-with-or-without-the-debugger.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C3%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708030026405510-211%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
