### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by JungYeolYang**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@JungYeolYang : Thanks for your contribution! The author, @conceptdev, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@SunnyDeng - this seems to be a submitted Korean translation of the article. Can you review?

Thanks.

**Comment by SunnyDeng** [comment]
@JasonCard can you please check the loc scope?

**Comment by JasonCard** [comment]
@SunnyDeng I found that this file is currently in localization. HB maybe delayed due to large amount of updates. Will follow up with loc vendor on ETA.

**Comment by conceptdev** [comment]
Note that this PR is against the English repo - it cannot be merged here. As Jason said, the page translation is in progress and will appear here https://docs.microsoft.com/ko-kr/visualstudio/mac/installation

**Comment by nschonni** [comment]
Looks like there is a problem with the deployment since the edit button on https://docs.microsoft.com/ko-kr/visualstudio/mac/installation points to this repo instead of the file in https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr

**Comment by conceptdev** [comment]
Thanks @nschonni I didn't notice that... seems like different behavior to what I've seen before; the loc team is on this thread so we'll figure it out!

**Comment by SunnyDeng** [comment]
@nschonni if there is no loc file existing in loc repo, then OPS will fall back the article to English version on DOCS, then the Edit is re-directed to the article in EN repo. 
For this article, seems EN article was published long time ago, but the loc version doesn't exist in the loc repo. Various reasons may caused this result. I'd like to wait for @JasonCard to confirm after he checkes the loc pipeline and schedule. 
Thank you for your patience!

**Comment by JasonCard** [comment]
@SunnyDeng Loc vendor found this file was put on hold via mistake, so they are following up on it, and we should know ETA tomorrow. In any case, should we ask Moravia Feedback team to move this PR to Korean repo?

**Comment by SunnyDeng** [comment]
@JasonCard thanks for checking! This one is a PR can't be transfer to ko-kr as an issue unless manually transfer. Let's prioritze this article release as much as we can. In the meanwhile, could you please pass the contributor translation to our production team as a loc reference?

**Comment by SunnyDeng** [comment]
@Jak-MS please close the PR here.

**Comment by JasonCard** [comment]
@SunnyDeng Yes, will do.

**Comment by JasonCard** [comment]
Hi @JungYeolYang,
Thank you for your contribution.
This article is now localized and published live: 
[https://docs.microsoft.com/ko-kr/visualstudio/mac/installation?view=vsmac-2019](https://docs.microsoft.com/ko-kr/visualstudio/mac/installation?view=vsmac-2019)

Kind regards,
Microsoft DOCS International Team
cc @SunnyDeng

**Pull request closed without merging**
