### PR TITLE
Add workaround for feedback auth proxy crash

### PR DESCRIPTION
**Pull request by nikolami**
Explains how to work around an issue in feedback.exe in Visual Studio 16.8 preview 3 and prior versions

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nikolami : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ornellaalt** [comment]
Hi @nikolami, does this only apply to Visual Studio 2019?

**Comment by nokola** [comment]
Changes apply to VS 2019 and 2017 in case 2019 is also installed on the same machine

**Comment by ornellaalt** [comment]
#sign-off

**Review by ornellaalt — APPROVED** [review]

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
