### PR TITLE
fix: MD010/no-hard-tabs

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by ktoliver** [comment]
Closing/reopening to trigger check completion

**Comment by ktoliver** [comment]
@gewarren Could you review this update? Thanks.

**Comment by gewarren** [comment]
@ktoliver Can we move this one to the private repo to check that the NOTE block is still indented appropriately?

**Comment by ktoliver** [comment]
@gewarren Yes, can do.

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @nschonni @gewarren - Private repo PR 4226 replaces this pull request. We moved the commit to the private repo so we can validate suggested formatting changes by using automated validation and staging. We'll close this PR now.

**Pull request closed without merging**
