### PR TITLE
Add instructions on using the project system tools extension

### PR DESCRIPTION
**Pull request by dmonroym**
We'd like to point users to a good documentation on how to collect binlogs which would in turn help the project-system team debug and analyze feedback items.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@dmonroym : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dmonroym** [comment]
@madskristensen @nikolami @swesonga for review

**Comment by dmonroym** [comment]
@corob-msft gentle ping. Could you help us get this approved and merged?

**Comment by corob-msft** [comment]
@dmonroym Sure, I'll take a look. My first impression is that this whole topic is badly in need of an update. Have you verified the command lines used? The ones for solution builds look suspicious to me, with double /d flags.

**Comment by dmonroym** [comment]
@BenVillalobos from the MSBuild team might be the right person to respond to that.

For now this change is simply intended to be useful so our customers have clear instructions on using the project-system-tools extension

**Comment by PRMerger12** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@dmonroym Please verify that my edits haven't told any lies. Otherwise LGTM.

**Comment by corob-msft** [comment]
@dmonroym If it looks good to you, then comment with hashtag **sign-off** to start the merge process. Builds are delayed with no ETA for a fix, so the content may not get built, merged, or published for some time.

**Comment by dmonroym** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@dmonroym: I'm sorry - only the author of this article, @corob-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by corob-msft** [comment]
D'oh!
#sign-off

**Comment by BenVillalobos** [comment]
Late to the party on this one, but it looks good :)

**Pull request merged**
