### PR TITLE
Update general-debugging-options-dialog-box.md

### PR DESCRIPTION
**Pull request by hharshada**
Removing the setting options which are not applicable with VS2022

### CODE REVIEW

**Comment by PRMerger17** [comment]
@hharshada : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Mikejo5000 — APPROVED** [review]

**Review by Mikejo5000 — CHANGES_REQUESTED** [review]
@hharshada Actually, I rechecked this. Can you restore the old content and put into a version-monikered section? It would look like this:
::: moniker range="<=vs-2022"
**Use Managed Compatibility Mode**
 ...old content
::: moniker-end
I'm assuming this option was present in VS 2019.

**Comment by hharshada** [comment]
Closing this as new PR is created

**Comment by Mikejo5000** [comment]
@hharshada Sure, that's fine. You might also just copy the markdown from the Files Changed tab above (it shows the old and new markdown) back into the PR. Here's the markdown:

**Use Managed Compatibility Mode**:
Replaces the default debugging engine with a legacy version to enable these scenarios:

- You are using a .NET language other than C#, Visual Basic, or F# that provides its own Expression Evaluator (this includes C++/CLI).

- You want to enable Edit and Continue for C++ projects during mixed mode debugging.

> [!NOTE]
> Choosing Managed Compatibility mode disables some features that are implemented only in the default debugging engine. The legacy debugging engine was replaced in Visual Studio 2012.

**Pull request closed without merging**
