### PR TITLE
Added Application Insights mention

### PR DESCRIPTION
**Pull request by CodeYoda**
Added the marketplace link for Application Insights and mentioned the usability of Application Insights for app development.  If we mention HockeyApp, Application Insights kind of goes hand in hand.

### CODE REVIEW

**Comment by gewarren** [comment]
@kraigb this is technically @TerryGLee 's topic, but this section is related to your Connected Services content like https://docs.microsoft.com/en-us/azure/vs-azure-tools-connected-services-storage. Can you take a look at this PR? It seems like the section might need to be updated as a whole to mention NuGet, and other possible changes.

**Comment by JennieHubbard** [comment]
@TerryGLee @gewarren

**Comment by kraigb** [comment]
The changes look fine; if you'd like some further updates, please create an item in the VSTS backlog for me.

**Comment by kraigb** [comment]
@TerryGLee there's a merge conflict on this one that I'll let you resolve...GitHub isn't giving me the option for some reason.

**Comment by gewarren** [comment]
I think this file was merged with the VS overview topic and deleted - hence no conflict resolution from GitHub. I'll take care of the conflict and merge this.

**Comment by gewarren** [comment]
Actually it looks like I was one step ahead of myself. The new App Insights content is already in the [Visual Studio Overview](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide#create-cloud-apps-for-azure) topic.

@CodeYoda thanks for your contribution!

**Pull request closed without merging**
