### PR TITLE
Add structure to VSIX manifest editor documentation

### PR DESCRIPTION
**Pull request by drewnoakes**
The prior documentation was flat and long, making it hard to understand the structure and segmentation of the information.

The diff here makes it hard to review. These are only formatting changes. The text remains unchanged.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@drewnoakes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
@leslierichardson95 - Could you review this proposed update to your article?

Thanks!

**Comment by ghogen** [comment]
@drewnoakes @ktoliver @leslierichardson95 
I've built this internally and it looks good. Thanks for the contribution.

**Review by ghogen — APPROVED** [review]

**Comment by ghogen** [comment]
The internal build is here; https://review.docs.microsoft.com/en-us/visualstudio/extensibility/vsix-manifest-designer?view=vs-2017&branch=pr-en-us-9175

**Comment by ktoliver** [comment]
@ghogen Thanks for creating the test build. We'll merge this pull request. Thanks, all.

**Pull request merged**
