### PR TITLE
Bump VSTU changelog to 3.4

### PR DESCRIPTION
**Pull request by sailro**
cc @jbevain @TerryGLee @gregvanl

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cross-platform/change-log-visual-studio-tools-for-unity.md](https://github.com/sailro/visualstudio-docs/blob/patch-6/docs/cross-platform/change-log-visual-studio-tools-for-unity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201709182224561946-293%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4qp%2BNuCgrOc3GbPhJpqcNcT6zeJ0I%2B0n%2BSSOGAz%2BRYU%3D&st=2017-09-18T22%3A21%3A37Z&se=2017-09-19T22%3A31%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cross-platform/change-log-visual-studio-tools-for-unity.md](https://github.com/sailro/visualstudio-docs/blob/patch-6/docs/cross-platform/change-log-visual-studio-tools-for-unity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201709182240507447-293%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Jw1GSnItlMFSRjx40lpZf7PWNvKnkqZI%2BUzB7Eki2aA%3D&st=2017-09-18T22%3A37%3A14Z&se=2017-09-19T22%3A47%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cross-platform/change-log-visual-studio-tools-for-unity.md](https://github.com/sailro/visualstudio-docs/blob/patch-6/docs/cross-platform/change-log-visual-studio-tools-for-unity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201709182241011942-293%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TEzvvQdBwjCbu9HFbFp%2ByfjQEp5iPJEGYMVre5KpjF4%3D&st=2017-09-18T22%3A47%3A47Z&se=2017-09-19T22%3A57%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sailro** [comment]
@TerryGLee thanks.

Unfortunately the content is still the old one online.  Could you check ?

**Pull request merged**
