### PR TITLE
Removed reference to MSDN

### PR DESCRIPTION
**Pull request by sguitardude**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@sguitardude : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger-2** [comment]
@Mikejo5000 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Mikejo5000 — APPROVED** [review]

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
