### PR TITLE
Added document for creating the feed using vsix util

### PR DESCRIPTION
**Pull request by ankitvarmait**
Added document for creating the feed using vsix util

### CODE REVIEW

**Comment by PRMerger8** [comment]
@ankitvarmait : Thanks for your contribution! The author(s) have been notified to review your proposed change. @anva

**Comment by ktoliver** [comment]
Hi @ghogen Could you look at this proposed new article and advise on how to proceed? If the content team accepts it, we can help move it to the private repo for automated QA checks, staging, and merge.

**Comment by j-martens** [comment]
@ghogen  for review

**Comment by ghogen** [comment]
@j-martens This was created in the private repo, so we can close this one here.
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8564

**Pull request closed without merging**
