### PR TITLE
fix: MD012/no-multiple-blanks

### PR DESCRIPTION
**Pull request by nschonni**
I've included the Find/Replace regex settings in VS Code used for both of the commits if you want to redo internally instead

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@nschonni : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're reviewing this pull request.

**Comment by gewarren** [comment]
@nschonni In general I think this looks good, but can you remove the docs/vs-2015/* files from this PR before we merge it? We don't generally accept updates to those files.

**Comment by nschonni** [comment]
@gewarren I can do that, but then the rule shouldn't be re-enabled in the Markdownlint config then, since it wouldn't be runnable (without errors) from the commandline.

**Pull request merged**
