### PR TITLE
Update azure-functions-lab.md

### PR DESCRIPTION
**Pull request by cmatskas**
Updated the Free Azure Subscription link to point to a page more relevant to the user

(You can replace all of this text with your description.)

Before creating your pull request, please check your content against these quality criteria:

- Did you consider search engine optimization (SEO) when you chose the title in the metadata section and the H1 heading (i.e. the displayed title that starts with a single #)?
- For new articles, did you add it to the table of contents?
- Did you update the "ms.date" metadata for new or significantly updated articles?
- Are technical terms and concepts introduced and explained, and are acronyms spelled out on first mention?
- Should this page be linked to from other pages or Microsoft web sites?

For more information about creating content for docs.microsoft.com, see the contributor guide at https://docs.microsoft.com/contribute/.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@cmatskas - can you sign the CLA? thanks.

**Comment by PRMerger13** [comment]
@cmatskas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
You can only sign off in the main PR conversation, not in review comments. In general, the creator of the PR should sign off, not the tech reviewer.

**Comment by cmatskas** [comment]
How? I don’t see that option anywhere...


________________________________

**Comment by sayedihashimi** [comment]
Christie, just leave a comment here with the text #sign-off like I did above.

**Pull request merged**
