### PR TITLE
Use abbreviated attribute names

### PR DESCRIPTION
**Pull request by drewnoakes**
Updates a code sample to use the more common form of attribute application.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@drewnoakes : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by drewnoakes** [comment]
@Jak-MS I haven't changed that specific code sample before, though I have made contributions on this repo before.

Would you please point me to the private repos?

**Comment by Jak-MS** [comment]
@drewnoakes,

It looks like you've already linked your GitHub alias with your Microsoft account, but if not, please follow the instructions in [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master). 

Once that's done, you can make content contributions through the private repository so the content can be staged and validated by the current validation rules.  
- [Contributor Guide](https://review.docs.microsoft.com/en-us/help/contribute/?branch=master).
- Private repo for visual studio docs is https://github.com/MicrosoftDocs/visualstudio-docs-pr .
- Read about [working in the public vs private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

Thank you.

**Comment by drewnoakes** [comment]
@Jak-MS thank you.

**Pull request merged**
