### PR TITLE
Added missing Step in the Complete Code

### PR DESCRIPTION
**Pull request by MarcoMue**
Added the missing Step from 6.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@anandmeg

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MarcoMue** [comment]
Is there anything else i need to do to merge this or get a response ?

**Comment by Court72** [comment]
Hi @marcomue, 

We're waiting for a review from the article's author.

@anandmeg,

Could you review this proposed update to your article and enter `#sign-off` in a comment if it's ready for merge?

**Review by anandmeg — APPROVED** [review]
@MarcoMue, thank you for your contribution.

**Comment by anandmeg** [comment]
#sign-off

**Pull request merged**
