### PR TITLE
Typo "Azure SQL database"→"Azure SQL Database"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/visualstudio/azure/azure-sql-database-add-connected-service?view=vs-2019
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger19** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by j-martens** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@j-martens: I'm sorry - only the author of this article, @AngelosP, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by j-martens** [comment]
@ktoliver @ghogen - can please help me get this merged?

**Review by AngelosP — APPROVED** [review]
Thank you so much for the edit :)

**Pull request merged**
