### PR TITLE
chore: Add GitHub Action for Markdownlint

### PR DESCRIPTION
**Pull request by nschonni**
This is the setup currently being used over on the dotent/docs repo to validate their Markdown content.
Note that this is currently failing https://github.com/nschonni/visualstudio-docs/runs/418742464?check_suite_focus=true#step:4:8

### CODE REVIEW

**Comment by ktoliver** [comment]
@jillre @ghogen Could you review the pull request? Thanks.

**Comment by ghogen** [comment]
@nschonni We'll discuss this internally and decide how to move forward. Thanks, Nick!

**Comment by nschonni** [comment]
No worries, you might want to get some of the feedback to see what edges were from the DotNet team https://github.com/dotnet/docs/pull/15184

**Comment by ghogen** [comment]
@nschonni Hi Nick!  We discussed this at our team meeting and decided that the disadvantages outweigh the advantages. Contributors can install the [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) to get Markdownlint feedback in their local editing environment.  Thanks again for your work improving the Visual Studio documentation!

**Comment by nschonni** [comment]
@ghogen I'm curious if you could share what the team saw as the disadvantages?

**Comment by ghogen** [comment]
@nschonni It takes extra time (iterations in a PR) to correct the issues reported, which means energy is focused on work that doesn't have a high strategic value vs. focusing more on customer scenarios and issues or looking at customer feedback.  We also would have to explain or answer questions about the issues or why the extra checks are there, and there's already a lot of other issues that users/contributors have to address, especially internally when engineers contribute to the docs.

**Pull request closed without merging**
