### PR TITLE
Fix description of get_modifierValues

### PR DESCRIPTION
**Pull request by Michael-K-Stein**
Old description was copy-pasted from get_PGOEntryCount

### CODE REVIEW

**Comment by Michael-K-Stein** [comment]
#sign-off

**Review by grantri — APPROVED** [review]

**Comment by grantri** [comment]
#sign-off

**Comment by grantri** [comment]
@Michael-K-Stein - I am the de-factor current owner of the DIA libraries. Thank you for these contributions.

**Comment by Michael-K-Stein** [comment]
@grantri - It is my pleasure. 
I'm currently working on a Python wrapper for the DIA SDK as a side project, so I've been reading up on the documentation quite a bit. Always glad to help out and be part of maintaining the excellent standard of MS-Docs. 
Cheers to the weekend!

**Pull request merged**
