### PR TITLE
Invalid XML in CodeCoverage data collector

### PR DESCRIPTION
**Pull request by b099l3**
The raised issue for this #6069
removed extra end tag

### CODE REVIEW

**Comment by PRMerger17** [comment]
@b099l3 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@b099l3 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- please review this customer PR.

**Review by Mikejo5000 — APPROVED** [review]
Looks good. Thanks!

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
