### PR TITLE
Update default-keyboard-shortcuts-in-visual-studio.md

### PR DESCRIPTION
**Pull request by pd-jam**
Add shortcut for Edit.SortUsings Ctrl-R, Crtrl-G - Removes unused using statements and sorts them into groups.

### CODE REVIEW

**Comment by pd-jam** [comment]
#sign-off

**Comment by pd-jam** [comment]
Thought I saw an instruction in the pull request pre-populated comments to make a comment with hash sign off.
Otherwise, I would not have done posted that comment.

**Comment by Court72** [comment]
@TerryGLee

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TerryGLee** [comment]
@pd-jam I'll sign off on this after I consult with the product team to confirm that the Sort Usings keyboard shortcut is valid, as the Edit.SortUsings command doesn't show that there's a shortcut for it in the product itself. 

image

**Comment by pd-jam** [comment]
Makes sense to me.  I don’t recall ever setting this keyboard shortcut over the past 2 or 3 Visual Studio versions – please do make it consistent with the product’s included keyboard shortcuts.

**Comment by TerryGLee** [comment]
OK. Before we can approve this PR, we must request that you make some changes to it, as follows:

Please change the "Sort Usings" entry to "Remove and sort usings". Then, change the command it's paired with from "Edit.SortUsings" to "EditorContextMenus.CodeWindow.RemoveAndSort" instead. 

Thanks in advance for doing this, and thanks for creating the PR, too. :)

**Review by TerryGLee — APPROVED** [review]

**Comment by TerryGLee** [comment]
@sign-off

**Pull request merged**
