### PR TITLE
instructions to use `user id` to add new user

### PR DESCRIPTION
**Pull request by prashantvc**
Added the troubleshooting guide while adding the new user

### CODE REVIEW

**Comment by PRMerger5** [comment]
@prashantvc : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by leslierichardson95** [comment]
#sign-off

**Comment by ktoliver** [comment]
We moved the commit to a new pull request in the private repo. The update will merge from there. We'll close this pull request. Thanks!

**Pull request closed without merging**
