### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_working_branch to master.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@cxwtool : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@Mikejo5000 Could you take a look to make sure the correct moniker year is retained? Select **Resolve conflicts** and scroll down to the yellow highlighted conflict. The conflict needs to be resolved and this PR merged for repo sync to resume. I think it pertains to https://github.com/MicrosoftDocs/visualstudio-docs/pull/7307, merged yesterday in the public repository. Thanks.

**Comment by PRMerger5** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
I'm resolving the conflict in favor of the latest update, for "2019" in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9079 (internal link). This conflicts with the update in https://github.com/MicrosoftDocs/visualstudio-docs/pull/7307, so @Mikejo5000 please check and follow up if needed. I'll merge this PR.

**Pull request merged**
