### PR TITLE
Update command syntax & necessary commands

### LINKED ISSUE #4728: Incorrect or outdated info on this doc
In this portion of the doc : https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---installpath
we are shown these 2 commands:

vs_enterprise.exe --update --quiet --wait
vs_enterprise.exe update --wait --passive --norestart --installPath "C:\installPathVS"

followed by this note : "Both commands are required. The first command updates the Visual Studio Installer. The second command updates the Visual Studio instance. To avoid a User Account Control dialog, run the command prompt as an Administrator."

Currently I am updating our visual studio 2017 version on our build farm and I am finding this to be incorrect.
If I load up my Visual studio installer UI via control panel, to update. It prompts that I must update my installer first.

On command line I use this single command: "vs_Professional.exe update --quiet --wait" and it updates both my installer and my vs2017 version.

Update the doc please.

I am running this command: "vs_Professional.exe update --quiet --wait"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---installpath)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

### PR DESCRIPTION
**Pull request by SeanKilleen**
Resolves #4728 (as far as I understand it).

(You can replace all of this text with your description.)

Before creating your pull request, please check your content against these quality criteria:

- Did you consider search engine optimization (SEO) when you chose the title in the metadata section and the H1 heading (i.e. the displayed title that starts with a single #)?
- For new articles, did you add it to the table of contents?
- Did you update the "ms.date" metadata for new or significantly updated articles?
- Are technical terms and concepts introduced and explained, and are acronyms spelled out on first mention?
- Should this page be linked to from other pages or Microsoft web sites?

For more information about creating content for docs.microsoft.com, see the contributor guide at https://docs.microsoft.com/contribute/.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@SeanKilleen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ornellaalt** [comment]
Hi @SeanKilleen, thank you for your contribution! I added some context in https://github.com/MicrosoftDocs/visualstudio-docs/issues/4728 and updated the documentation slightly differently. Please let me know if you have any questions.

**Comment by SeanKilleen** [comment]
Hi @ornellaalt, in the future it would be great to work on a PR together and get it merged rather than addressing it separately. I would have been willing to work with you on that since I'd already invested some time.

But, glad it's resolved! 👍

**Comment by ornellaalt** [comment]
Hi @SeanKilleen, sorry about that, and looking forward to collaborating in the future!

**Pull request closed without merging**
