### PR TITLE
Screenshot of installing a NuGet package

### PR DESCRIPTION
**Pull request by dixonsj**
image for Add usings for types in reference assemblies and NuGet packages

### CODE REVIEW

**Comment by PRMerger6** [comment]
@dixonsj : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@dixonsj Can you give some more context for adding this image? Which topic does it appear in? Thanks.

**Comment by dixonsj** [comment]
Hi.

It was meant to be with a seperate or for PR for https://github.com/MicrosoftDocs/visualstudio-docs/issues/1614

I updated the section on using directives but wanted to add a snippet to show the add reference to nuget package.

Thanks

Shane.
________________________________

**Comment by gewarren** [comment]
This is the [PR ](https://github.com/dixonsj/visualstudio-docs/pull/1) the image goes with, however the PR is only in the user's fork at this point.

**Comment by gewarren** [comment]
@dixonsj Can you submit a new PR that combines the screenshot with the text you want to add, or add the text to this PR? Thanks.

**Comment by dixonsj** [comment]
Sorry about that mess.

I have created a new PR https://github.com/MicrosoftDocs/visualstudio-docs/pull/1668

Thanks,

Shane.

**Pull request closed without merging**
