### PR TITLE
First round of updates, covering cloud subscription purchasing and FAQ, bringing the CSP cloud subscription content in, bringing the alternate identity page in, and deleting superfluous pages.

### PR DESCRIPTION
**Pull request by JuniorIce**

### CODE REVIEW

**Comment by gewarren** [comment]
@JuniorIce has this been reviewed and ready to merge?

**Comment by JuniorIce** [comment]
Adding my Microsoft alias too. I think Evan needs to review. There are a couple pages where the GitHub preview of tables looks weird, not sure if those will still look weird on our site. The markdown syntax appears to be right.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gewarren** [comment]
@JuniorIce if you submit this PR to the private repo (visualstudio-docs-pr), which is preferred for Microsoft employees, you will get staging links so you can see how the content would look after it's published. If you can't access that repo, associate your GitHub id with your Microsoft account, and then join the MicrosoftDocs organization.

**Comment by JuniorIce** [comment]
dropping this, will redo a PR against the private repo

**Pull request closed without merging**
