### PR TITLE
Update quickstart-deploy-to-a-web-site.md

### PR DESCRIPTION
**Pull request by AlexB-SheldonMFG**
#5664, Write-the-Docs-2020

### CODE REVIEW

**Comment by PRMerger15** [comment]
@AlexB-SheldonMFG : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@Mikejo5000 - The [guidance provided](https://docs.microsoft.com/style-guide/procedures-instructions/describing-interactions-with-ui) for the Write-the-Docs says to replace "right-click" with "select and hold (or right-click)". Would you like the PR review team to make this change and then merge the PR? (It looks like several PRs were open for this issue.)

Thanks.

**Comment by Mikejo5000** [comment]
As per comments in the other PR, for VS we will likely prefer "right-click" over select-and-hold.

**Comment by ghogen** [comment]
Looking at this further, it looks like this is not a correct change. Thanks for your contribution, however for this change, we'll have to close without merging.

**Pull request closed without merging**
