### PR TITLE
Update idiainjectedsource.md

### PR DESCRIPTION
**Pull request by tim-weis**
Fixes copy-paste errors in sample.

#sign-off

### CODE REVIEW

**Comment by Court72** [comment]
@Mikejo5000

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by Mikejo5000 — APPROVED** [review]
Looks good. Thanks!

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by tim-weis** [comment]
That was prompt. Thank you both!

After years of contributing, I'm still dumbfounded at how convenient it is to go from *"This can't be right..."* to *"That makes perfect sense!"* Without ever leaving my keyboard. Kudos to whoever made this possible. This is incredibly useful to myself and hopefully others, too!

The automated PR experience could be improved, though. Upon committing my changes and generating a PR, I was presented with instructions bracketed in an `<!-- -->` XML comment block[^1]. The comment template—in hindsight—appears to have been directed towards members of the Microsoft organization only. Anyone outside the organization is a victim of misinterpretation[^2].

Could the template be reworded to be meaningful to those who aren't part of the Microsoft organization?

[^1]: I deleted the text after I worked through it, so I'm lacking in details.
[^2]: I added the `#sign-off` token to my PR to signal that it's ready to be merged. I created a test application, copied the sample code, and verified that it compiled, linked, and ran. I went ahead to implement a test and corresponding input to make it fail, applied the fix, re-verified that it compiled, linked, and ran, and observed that the test succeeded. Only to find out later that the instructions weren't meant for me.

**Pull request merged**
