### PR TITLE
Update lightweight-solution-load-extension-impact.md

### PR DESCRIPTION
**Pull request by LukaszMendakiewicz**
VSPROPID_DeferredProjectCount is int property

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/extensibility/lightweight-solution-load-extension-impact.md](https://github.com/LukaszMendakiewicz/visualstudio-docs/blob/patch-1/docs/extensibility/lightweight-solution-load-extension-impact.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201707180355419138-192%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LukaszMendakiewicz** [comment]
@RodrigoVaras you may want to take a look.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/extensibility/lightweight-solution-load-extension-impact.md](https://github.com/LukaszMendakiewicz/visualstudio-docs/blob/patch-1/docs/extensibility/lightweight-solution-load-extension-impact.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201707180657597729-192%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gregvanl** [comment]
Thanks!

**Pull request merged**
