### PR TITLE
remove redundant string conversions

### PR DESCRIPTION
**Pull request by SimonCropp**
string variables dont need to be wrapped in `'`

### CODE REVIEW

**Comment by PRMerger12** [comment]
@SimonCropp : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@SimonCropp Looks good. Thanks!

**Comment by Mikejo5000** [comment]
Reverted as part of #4474

**Comment by Mikejo5000** [comment]
...in the private repo

**Pull request merged**
