### PR TITLE
V2515: Broken link

### PR DESCRIPTION
**Pull request by v-makoud**
Hello @TerryGLee,
there is a broken link in the page in this string:
For a related video demonstration, see How do I: Automate PowerPoint from an Excel Add-in?.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@v-makoud : Thanks for your contribution! The author, @TerryGLee, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @v-makoud - The changes in the PR should have been made via the private repository, azure-docs-pr. The private repo has better validation and QA, so Microsoft contributors are expected to use that channel. Please submit future updates through the private repo.

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information. 

Thanks.

**Comment by TerryGLee** [comment]
@v-makoud Thanks for your suggestion. As @ktoliver suggested, a request such as this from an internal-to-Microsoft person should be made through our private repo, visualstudio-docs-pr. We will close this public PR shortly. 
@John-Hart - FYI.

**Comment by TerryGLee** [comment]
#hold-off

**Comment by v-makoud** [comment]
new PR in pr: 3352

**Pull request closed without merging**
