### PR TITLE
Adding a Tip about associating work items with commits

### PR DESCRIPTION
**Pull request by Taysser-Gherfal**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Taysser-Gherfal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TerryGLee** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@TerryGLee: I'm sorry - only the author of this article, @prnadago, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by TerryGLee** [comment]
fixes https://github.com/MicrosoftDocs/visualstudio-docs/issues/5973

**Comment by ktoliver** [comment]
@TerryGLee will edit, per email.

**Pull request merged**
