### PR TITLE
Update adding-a-menu-to-the-visual-studio-menu-bar

### PR DESCRIPTION
**Pull request by Asugakoisi**
I deleted the difference in the explanation between  `vs2017` and  `vs2019`, 
because I could't find the difference when I try this tutorial.

### CODE REVIEW

**Comment by ktoliver** [comment]
@acangialosi 

Could you review the proposed changes to your article?

Thanks!

**Comment by PRMerger10** [comment]
@Asugakoisi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@leslierichardson95 - Would you be able to review/resolve this pull request, or recommend someone who can? Thanks.

cc @TerryGLee

**Comment by leslierichardson95** [comment]
#hold-off

@Asugakoisi I'm rejecting this PR because some of the file names change between vs2017 and vs2019 (ie. 2019 uses TopLevelMenuPackage.vsct and 2017 uses TestCommandPackage.vsct).

**Comment by TerryGLee** [comment]
@Asugakoisi I am closing this PR per @leslierichardson95's input; we thank you for your input and we hope to hear from you again.

**Pull request closed without merging**
