### PR TITLE
Fix minor issues in tool-require-psmodule.md

### PR DESCRIPTION
**Pull request by aurichar**
- Fix malformed link
  - Fix malformed !TIP field

### CODE REVIEW

**Comment by PRMerger8** [comment]
@aurichar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by gregvanl** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@gregvanl: I'm sorry - only the author of this article, @andysterland, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by gregvanl** [comment]
Fixes applied in the private branch

**Pull request closed without merging**
