### PR TITLE
add section for Module suppression scope

### PR DESCRIPTION
**Pull request by carlin-q-scott**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@carlin-q-scott : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@mavasani and @mikadumont for review

**Comment by Mikejo5000** [comment]
@mavasani @mikadumont OK to merge this?

**Comment by Mikejo5000** [comment]
#sign-off Thanks!

**Pull request merged**
