### PR TITLE
Update certificate info for offline installs

### PR DESCRIPTION
**Pull request by frayus**
For Visual Studio 2017 Update 8, creating a layout will now generate a certificates folder with just the root certificates.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@frayus : Thanks for your contribution! The author, @TerryGLee, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@frayus : Thanks for your contribution! The author, @TerryGLee, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@frayus : Thanks for your contribution! The author, @TerryGLee, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@frayus : Thanks for your contribution! The author, @TerryGLee, has been notified to review your proposed change.

**Comment by TerryGLee** [comment]
#sign-off

**Pull request merged**
