### PR TITLE
ms-updates6.3

### PR DESCRIPTION
**Pull request by NickyArias**
Updating the existing Dotfuscator section to match the Dotfuscator Community 6.3 user guide.
There are two new pages created for this update:
- Register Dotfuscator Community
- Upgrade from Dotfuscator Community 5
 
In these new pages there is some metadata missing (ms.assetid, author, ms.author, and manager).
Can you please provide that information?
Thank you.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@NickyArias : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @TerryGLee The new content, if you accept it for publishing, should be moved to the private repo for QA checks and merging. You can move the commit and retain the contributor association. Let me know if you'd like the PR review team to help with this. (If I move the commit, the new pull request in the private repo will be in my fork, FYI.)

**Comment by ktoliver** [comment]
@NickyArias Thanks for your new content submission. The content team will review it.

**Comment by TerryGLee** [comment]
@ktoliver Yes, I'd appreciate your help in moving this to the private repo. @NickyArias, I'll reach out to you via email to send you some links to our Contributors Guide so that you'll know how to create your PRs in the private repo, going forward. And, thanks for your contribution!

**Comment by ktoliver** [comment]
We'll move the commit to the private repo. I'll post here when the new pull request is open.

**Comment by ktoliver** [comment]
#hold-off

**Comment by ktoliver** [comment]
The commit has been moved to a new pull request in the private repo, where it will be merged. We'll close this PR. Thanks.

**Comment by NickyArias** [comment]
Thanks you @ktoliver.
Will there be a notification when the new pull request is merged?

**Comment by TerryGLee** [comment]
@NickyArias To follow up, the PR has been merged and the new pages are live:

- https://docs.microsoft.com/en-us/visualstudio/ide/dotfuscator/register?view=vs-2019
- https://docs.microsoft.com/en-us/visualstudio/ide/dotfuscator/upgrade-from-5?view=vs-2019

**Comment by NickyArias** [comment]
> 
> 
> @NickyArias To follow up, the PR has been merged and the new pages are live:
> 
>     * https://docs.microsoft.com/en-us/visualstudio/ide/dotfuscator/register?view=vs-2019
> 
>     * https://docs.microsoft.com/en-us/visualstudio/ide/dotfuscator/upgrade-from-5?view=vs-2019

@TerryGLee thank you for letting me know that.

**Pull request closed without merging**
