### PR TITLE
Update toc.yml (Typo ".Sln"→".sln")

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2022
https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/extensibility/internals/toc.yml
related #7982 (Typo ".Sln"→".sln")
#PingMSFTDocs

### CODE REVIEW

**Comment by Jak-MS** [comment]
#assign: @ghogen 

@ghogen - can you take a look? Thanks!

IMPORTANT: When this content is ready to merge, the reviewer must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"

**Review by TerryGLee — APPROVED** [review]

**Comment by TerryGLee** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@TerryGLee: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ghogen** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ghogen: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
