### PR TITLE
Updated organizaton from Microsoft to MicrosoftDocs and another minor correction

### PR DESCRIPTION
**Pull request by alfredmyers**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/CONTRIBUTING.md) | :white_check_mark:Succeeded | |
[docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C10%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708101551497089-228%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by alfredmyers** [comment]
I signed the CLA. Do I have to do anything else?

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/CONTRIBUTING.md) | :white_check_mark:Succeeded | |
[docs/profiling/TOC.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/TOC.md) | :white_check_mark:Succeeded | |
[docs/profiling/beginners-guide-to-performance-profiling.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/beginners-guide-to-performance-profiling.md) | :white_check_mark:Succeeded | |
[docs/profiling/how-to-collect-performance-data-for-a-web-site.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/how-to-collect-performance-data-for-a-web-site.md) | :white_check_mark:Succeeded | |
[docs/profiling/profiling-feature-tour.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/profiling-feature-tour.md) | :white_check_mark:Succeeded | |
[docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C13%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708131546073400-228%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/CONTRIBUTING.md) | :white_check_mark:Succeeded | |
[docs/profiling/beginners-guide-to-performance-profiling.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/beginners-guide-to-performance-profiling.md) | :white_check_mark:Succeeded | |
[docs/profiling/how-to-collect-performance-data-for-a-web-site.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/how-to-collect-performance-data-for-a-web-site.md) | :white_check_mark:Succeeded | |
[docs/profiling/profiling-feature-tour.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/profiling-feature-tour.md) | :white_check_mark:Succeeded | |
[docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708182118174451-228%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/CONTRIBUTING.md) | :white_check_mark:Succeeded | |
[docs/profiling/beginners-guide-to-performance-profiling.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/beginners-guide-to-performance-profiling.md) | :white_check_mark:Succeeded | |
[docs/profiling/how-to-collect-performance-data-for-a-web-site.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/how-to-collect-performance-data-for-a-web-site.md) | :white_check_mark:Succeeded | |
[docs/profiling/profiling-feature-tour.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/profiling-feature-tour.md) | :white_check_mark:Succeeded | |
[docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708182119529551-228%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/CONTRIBUTING.md) | :white_check_mark:Succeeded | |
[docs/profiling/beginners-guide-to-performance-profiling.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/beginners-guide-to-performance-profiling.md) | :white_check_mark:Succeeded | |
[docs/profiling/how-to-collect-performance-data-for-a-web-site.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/how-to-collect-performance-data-for-a-web-site.md) | :white_check_mark:Succeeded | |
[docs/profiling/profiling-feature-tour.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/profiling-feature-tour.md) | :white_check_mark:Succeeded | |
[docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md](https://github.com/alfredmyers/visualstudio-docs/blob/patch-1/docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C18%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708182122453515-228%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
