### PR TITLE
checking the redirections for the task 25329 

### PR DESCRIPTION
**Pull request by EstherGaddindla**

### CODE REVIEW

**Comment by ktoliver** [comment]
@Mikejo5000 - Would you review the proposed changes? Thanks.

**Comment by Mikejo5000** [comment]
I believe Esther is running initial tests here, and there will be a big update to this PR later.

**Comment by Mikejo5000** [comment]
Esther is planning to commit a large set of changes, likely in this PR. The current change is an initial test.

**Comment by GitHubber17** [comment]
Hi @Mikejo5000 @EstherGaddindla - Microsoft authors need to make updates through the private repository so the updates can be staged and validated by the current validation rules.

You can read about [article authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.

Is there a business reason these changes are being submitted through the public repository? Thanks

**Pull request closed without merging**
