### PR TITLE
Update how-to-create-an-xml-document-based-on-an-xsd-schema.md #5664

### PR DESCRIPTION
**Pull request by caro-oviedo**
#5664

### CODE REVIEW

**Comment by PRMerger20** [comment]
@caro-oviedo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@caro-oviedo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Verified the revisions; merging.

**Comment by ghogen** [comment]
@ktoliver The change at line 19 of "how-to-edit-xml-files.md" is incorrect - normally, we would just say "Open" rather than reference the specific tapping or clicking action (you can also use the keyboard).  But in this case, since it seems to be telling people how to open a file, "double-click or double tap" is probably best.

**Pull request merged**
