### PR TITLE
Update display-data-in-blend.md

### PR DESCRIPTION
**Pull request by mgoertz-msft**
Added Note for what types of projects support the Data panel

### CODE REVIEW

**Comment by PRMerger15** [comment]
@mgoertz-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgoertz-msft** [comment]
@gewarren I added a (slightly modified) note as suggested. Please review. Thank you!

**Comment by TerryGLee** [comment]
#sign-off

**Comment by mgoertz-msft** [comment]
Thank you. Someone needs to merge that for me as it says I'm not authorized to do that.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
