### PR TITLE
Add information to Framework switch

### PR DESCRIPTION
**Pull request by nohwnd**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@nohwnd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mavasani** [comment]
Tagging @ManishJayaswal @kendrahavens - probably someone from the test team should review this.

**Comment by ManishJayaswal** [comment]
@kendrahavens @pavelhorak - please review this.

**Comment by Mikejo5000** [comment]
Thanks for the correction. Yes, should be Test team.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
