### PR TITLE
Update isolating-code-under-test-with-microsoft-fakes.md

### PR DESCRIPTION
**Pull request by scott-xu**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@scott-xu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@AbhitejJohn Please take a look at this one. Thanks!

**Review by AbhitejJohn — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
