### PR TITLE
Add missing links

### PR DESCRIPTION
**Pull request by paulomorgado**
Add missing links to currently released documentation.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@paulomorgado : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
#sign-off LG. Thanks!

**Comment by ktoliver** [comment]
Hi @paulomorgado Could you update your branch so the merge conflicts will be resolved? I think that action would be more efficient and accurate than manually resolving the merge conflict by using the GitHub UI. Then we can merge the PR. Thanks!

**Comment by PRMerger9** [comment]
@paulomorgado : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@paulomorgado : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@paulomorgado : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @paulomorgado

**Pull request merged**
