### PR TITLE
Replace transparent background with white for readability

### LINKED ISSUE #2222: Text in image not visible
Some of the text in the first image (0501-a_commandplacement.png) under section "Command placement decisions" is barely visible in the Dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 997573f6-37fb-876a-f6c6-0cb857a52f92
* Version Independent ID: c14c634c-8321-f995-2114-6a039baf93fb
* Content: [Menus and Commands for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/menus-and-commands-for-visual-studio?view=vs-2017#command-placement-decisions)
* Content Source: [docs/extensibility/ux-guidelines/menus-and-commands-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/menus-and-commands-for-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

### PR DESCRIPTION
**Pull request by Nacimota**
Fixes #2222 by replacing the transparent background of the image with a white background.

### CODE REVIEW

**Comment by gregvanl** [comment]
Looks good. Thanks for doing this.
#sign-off

**Comment by PRMerger19** [comment]
@gregvanl: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
closing/reopening PR to trigger complete status check for CLA

**Comment by PRMerger7** [comment]
@Nacimota : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Pull request merged**
