### PR TITLE
Adding rules to security-warnings page

### PR DESCRIPTION
**Pull request by eddynaka**
renaming files to be more friendly, adding links to security page

### CODE REVIEW

**Comment by PRMerger18** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by gewarren** [comment]
@eddynaka Thanks for adding the rules to the Security Warnings page. I know that these file names are different to the ones that came before them, however we recently switched to naming new files with just the rule ID. Could you undo the rename changes?

**Comment by eddynaka** [comment]
Ok. No problem.

I will update those :)

**Comment by PRMerger6** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger6** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger7** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@eddynaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by eddynaka** [comment]
@gewarren just updated as u commented before. Can you check?

**Comment by eddynaka** [comment]
@gewarren , can i update the other documents as well? Thanks!

**Comment by gewarren** [comment]
> @gewarren , can i update the other documents as well? Thanks!

Sure, thanks!

**Pull request merged**
