### PR TITLE
Add changelog entries for Visual Studio Tools for Unity (VSTU), v3.2, v3.3 and v3.4

### PR DESCRIPTION
**Pull request by sailro**

### CODE REVIEW

**Comment by sailro** [comment]
cc @jbevain

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cross-platform/change-log-visual-studio-tools-for-unity.md](https://github.com/sailro/visualstudio-docs/blob/patch-4/docs/cross-platform/change-log-visual-studio-tools-for-unity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C9%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708091706536213-222%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cross-platform/change-log-visual-studio-tools-for-unity.md](https://github.com/sailro/visualstudio-docs/blob/patch-4/docs/cross-platform/change-log-visual-studio-tools-for-unity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C9%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708091713216069-222%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sailro** [comment]
cc @gregvanl

**Pull request merged**
