### PR TITLE
Update multitooltask-task.md

### PR DESCRIPTION
**Pull request by DavidBuerer**
Added brief summary from https://devblogs.microsoft.com/cppblog/improved-parallelism-in-msbuild/ so that the page has some value.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@DavidBuerer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@ghogen 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger15** [comment]
@ghogen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ghogen** [comment]
#sign-off

**Pull request merged**
