### PR TITLE
Fixed typos on ClickOnce docs

### PR DESCRIPTION
**Pull request by alfredmyers**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@alfredmyers : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@Mikejo5000 - Could you review the PR? I think the backslashes are intended to work as escape characters here. Thanks.

**Comment by PRMerger17** [comment]
@alfredmyers : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by alfredmyers** [comment]
> @Mikejo5000 - Could you review the PR? I think the backslashes are intended to work as escape characters here. Thanks.

@ktoliver , @Mikejo5000 FYI, The existence of those backslashes result in what was supposed to be links to pages on API docs not being rendered.

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
