### PR TITLE
Update how-to-use-rule-based-ui-context-for-visual-studio-extensions.md

### PR DESCRIPTION
**Pull request by ArntWork**
Fix VSConstants.UICONTEXT_SolutionHasSingleProject_string to VSConstants.UICONTEXT.SolutionHasSingleProject_string (dot after UICONTEXT).

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ArntWork : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by leslierichardson95** [comment]
sign-off

**Comment by leslierichardson95** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@leslierichardson95: I'm sorry - only the author of this article, @acangialosi, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
