### PR TITLE
MSBuild: Exists doesn't glob

### PR DESCRIPTION
**Pull request by rainersigwald**
If you have a condition like `Condition="Exists('something*.dll')"`, it always returns `false`.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@rainersigwald : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@ghogen

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ghogen** [comment]
We're now part of a pilot program to test builds for public PRs. Closing and reopening to see if a build is triggered.

**Review by ghogen — APPROVED** [review]

**Comment by ghogen** [comment]
#sign-off

**Pull request merged**
