### PR TITLE
Added some links to PIAs; light edit pass

### PR DESCRIPTION
**Pull request by ghost**
Our team (Office Developer) is migrating some of the PIAs from MSDN, and we wanted to add visibility to their new location, so I added links to the ones we know of in the table.

As an editor, I also did a light edit pass on the topic to fix some broken formatting and typos.

Let me know if you have any questions.

### CODE REVIEW

**Comment by Linda-Editor** [comment]
For the "office.dll" entry in the table, check to see if this link is the appropriate target: 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.core?view=office-pia

**Comment by TerryGLee** [comment]
@Linda-Editor Thanks for your contribution! I will approve this but please see the email that I sent you under separate cover. :)


#sign-off

**Comment by Linda-Editor** [comment]
@ktoliver Is there a reason these changes aren't showing up on stage? https://review.docs.microsoft.com/en-us/visualstudio/vsto/office-primary-interop-assemblies?branch=master&view=vs-2017

Or am I using the wrong link?

**Comment by ktoliver** [comment]
Hi @Linda-Editor - In the public repos, pull request content is not staged. You can check your updates only by using GitHub Preview before merging. For more information, see [Why work in the private repo?](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master#why-work-in-the-private-repo)

**Comment by ktoliver** [comment]
As a PR reviewer, I'm not involved in publishing. The visualstudio-docs repo owners might have this information - @ghogen @gewarren

**Comment by gewarren** [comment]
We publish daily around 11 am.

**Pull request merged**
