### PR TITLE
Fixes example for dynamic data

### PR DESCRIPTION
**Pull request by gfs**
The nameof call and static data source did not have matching names.

### CODE REVIEW

**Comment by Court72** [comment]
@Mikejo5000 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Mikejo5000** [comment]
@Evangelink to verify. The fix looks right to me.

**Review by Evangelink — APPROVED** [review]
LGTM - Thanks for the contribution @gfs

**Review by Mikejo5000 — APPROVED** [review]

**Comment by Mikejo5000** [comment]
#sign-off Thanks!

**Pull request merged**
