### PR TITLE
Correct class name

### PR DESCRIPTION
**Pull request by tonyhallett**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@tonyhallett : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by tonyhallett** [comment]
There are other issues with https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/colors-and-styling-for-visual-studio?view=vs-2019&source=docs

The links on this page do not exist
> The table at WPF Team Blog: SystemColors Reference indicates the complete set of system color names, and the corresponding hues displayed in each theme.

Code examples use SolutionExplorerColors.  In which dll is this defined ?
It is not in Microsoft.VisualStudio.Shell.15.0/16.0.0.0, Microsoft.VisualStudio.Shell.Framework 16.0.0.0 ( or Microsoft.VisualStudio.Shell.UI.Internal )

```
button.BackColor = GetThemedGDIColor(shell5, SolutionExplorerColors.SelectedItemBrushKey);
```

**Comment by tonyhallett** [comment]
This repo could be of use https://github.com/github/VisualStudio/tree/master/src/GitHub.VisualStudio.UI/Themes

Also for High Contrast
From https://docs.microsoft.com/en-us/windows/apps/design/accessibility/high-contrast-themes
image

The ThemeResourceKey objects

EnvironmentColors.SystemWindowTextColorKey
-
EnvironmentColors.ControlLinkTextColorKey
EnvironmentColors.ControlLinkTextHoverColorKey
EnvironmentColors.ControlLinkTextPressedColorKey
-
EnvironmentColors.SystemGrayTextColorKey
EnvironmentColors.SystemHighlightTextColorKey
EnvironmentColors.SystemHighlightColorKey
EnvironmentColors.SystemButtonTextColorKey
EnvironmentColors.SystemButtonFaceColorKey
EnvironmentColors.SystemWindowColorKey

**Comment by tonyhallett** [comment]
Other ThemeResourceKey objects ( in addition to those from EnvironmentColors ) from properties of

CommonControlsColors
TreeViewColors
StartPageColors
CommonDocumentColors
HeaderColors
InfoBarColors
ProgressBarColors
SearchControlColors
ThemedDialogColors
UnthemedDialogColors
VisualStudioInstallerColors

( and there are some in Shell.UI.Internal )

**Comment by tonyhallett** [comment]
When discussing IVsFontAndColorStorage, https://github.com/microsoft/VS-ColorThemes is a good source for obtaining category Guids for `OpenCategory`.   

https://github.com/microsoft/VS-ColorThemes/blob/25958bd61f94192360fcdd8a2f9c9be4232e1997/VSColorThemes/Themes/PlainDark.xml#L7142

```
    <Category Name="Text Editor Text Marker Items" GUID="{ff349800-ea43-46c1-8c98-878e78f46501}">
      <Color Name="Coverage Touched Area">
        <Background Type="CT_RAW" Source="FF9BD1E1" />
        <Foreground Type="CT_RAW" Source="FF000000" />
      </Color>
      <Color Name="Coverage Not Touched Area">
        <Background Type="CT_RAW" Source="FFEDE0D1" />
        <Foreground Type="CT_RAW" Source="FF000000" />
      </Color>
      <Color Name="Coverage Partially Touched Area">
        <Background Type="CT_RAW" Source="FFB4B6CB" />
        <Foreground Type="CT_RAW" Source="FF000000" />
      </Color>
```
For

image

**Comment by tonyhallett** [comment]
It would also be beneficial to add the EnvironmentColors that correspond to the [Usage Patterns](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/colors-and-styling-for-visual-studio?view=vs-2019&source=docs#usage-patterns)

SystemActiveCaptionColorKey
SystemCaptionTextBrushKey
**SystemThreeDFaceColorKey
SystemThreeDShadowColorKey
SystemThreeDDarkShadowColorKey
SystemThreeDLightShadowColorKey
SystemThreeDHighlightColorKey
ButtonTextColorKey**
SystemGrayTextColorKey
SystemHighlightColorKey
SystemHighlightTextColorKey
** cannot find entry for hottrack** this [link](https://www.syncfusion.com/faq/windowsforms/from-gdi/how-do-the-win32-system-colors-map-to-the-colors-provided-by-system-drawing-systemcolors) suggest it is the same as Highlight.  Perhaps it is 
LightColorKey
SystemInactiveCaptionColorKey
SystemInactiveCaptionTextColorKey
SystemMenuColorKey
SystemMenuTextColorKey
SystemScrollBarColorKey
SystemWindowColorKey
SystemWindowFrameColorKey
SystemWindowTextColorKey

**Review by mj559940 — APPROVED** [review]

**Comment by leslierichardson95** [comment]
#sign-off

**Pull request merged**
