### PR TITLE
Update build and deploy of iOS app OpenGL ES

### PR DESCRIPTION
**Pull request by michelleangela**
Update instructions for building and deploying an iOS OpenGL ES app
- Add instructions to setup signing on Xcode
- Remove instructions for deploying to simulator
- Add instructions for deploying to iOS device

### CODE REVIEW

**Comment by PRMerger16** [comment]
@michelleangela : Thanks for your contribution! The author, @corob-msft, has been notified to review your proposed change.

**Comment by michelleangela** [comment]
@corob-msft , thanks for reviewing the changes for vcremote.

Here is another to update iOS build and deploy to iOS device.

**Comment by PRMerger13** [comment]
@corob-msft : Thanks for your contribution! The author, @corob-msft, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@michelleangela @corob-msft - PRs of this size need to be created in the private repos where we can take advantage of staging and validation.  Can you push the commits in this branch to the private repo and sign off there?  Let me know if you need help doing that.  Thanks.

**Comment by PRMerger18** [comment]
@michelleangela : Thanks for your contribution! The author, @corob-msft, has been notified to review your proposed change.

**Comment by michelleangela** [comment]
> @michelleangela
> Thanks for the updates. I also updated the Requirements section for VS 2017 and VS 2019, and made some editorial changes to make our grammar checker happy.

Thanks for the additional changes. I added one more image ref  to the doc.

**Comment by michelleangela** [comment]
> @michelleangela @corob-msft - PRs of this size need to be created in the private repos where we can take advantage of staging and validation. Can you push the commits in this branch to the private repo and sign off there? Let me know if you need help doing that. Thanks.

That does mean check-in the changes to my private forked repo? And then merge the private repo to the upstream master?

**Comment by Jak-MS** [comment]
@michelleangela - first you need to have access to the private repository - visualstudio-docs-pr  and then you can follow this process here: https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master#pull-public-commits-to-the-private-repo-for-updates-staging-publication 

If you don't have access you can set that up, but it depends on if you'll be needing it more than this one time.  If not, I can move the branch for you (after you're completely done), but you won't be able to follow the PR in the private repo. Just let us know. Thanks

***
Note: 
If you're a content pro (writer or PM) you shold be working in the private repos. I'm not 100% sure that applies to you. If it does then read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Comment by corob-msft** [comment]
@michelleangela 
I recommend that you do both - Follow the [Github account setup](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master) instructions to enable access to the private repo, *and* take up @Jak-MS on his offer to make a branch for the PR in the private repo and transfer the commits. Then you can follow the process along. And, you'll be prepared if you have significant changes to make in the future.

**Comment by michelleangela** [comment]
@corob-msft thanks, I joined the team **MicrosoftDocs** and now have access to **visualstudio-docs-pr**.

@Jak-MS, yes, I'll take your offer on transferring the PR over to the private repo. For context, I'm the dev helping maintain this Visual Studio feature/workload. I don't anticipate making document updates often, but in case we need to in the future, I'll use the private repo.

**Comment by Jak-MS** [comment]
@michelleangela @corob-msft - sounds good. We will link the new PR to this one when it's ready for review and sign off. Please confirm that this PR and branch contains all the commits you want moved. Thanks.

**Comment by michelleangela** [comment]
No pending changes from me. Waiting for @corob-msft for final approval.

**Comment by corob-msft** [comment]
It looks good. I'll sign off the changes in the private repo.

**Comment by Jak-MS** [comment]
Thank you for confirmation @michelleangela and @corob-msft . 

I should have time to move these commits today (if another one of my team doesn't get to it first). We will update this PR with the new private repo PR. Thanks!

**Comment by Jak-MS** [comment]
New PR is https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/4647

**Comment by Jak-MS** [comment]
As this his being handled in the private repo, we're closing this PR.

#please-close

**Pull request closed without merging**
