### PR TITLE
Add documentation about data breakpoint errors

### PR DESCRIPTION
**Pull request by WardenGnaw**
This PR adds two md files about errors with managed data breakpoints
"unable to set data breakpoint" errors and hardware supported data
breakpoints.

error-unable-to-set-data-breakpoint.md:
	Explains the errors messages you may get when using managed data
	bps and how to either solve/workaround the issue
hard-ware-supported-data-breakpoints.md:
	Displays a table on the number of supported hardware breakpoints
	and the limit of bytes it can watch

@mikejo5000
@caslan

### CODE REVIEW

**Comment by PRMerger9** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by Mikejo5000** [comment]
@WardenGnaw Andrew, Leslie said she would forward you an email on making contributions on the private repo (visualstudio-docs-pr). It looks like the link above to the instructions doesn't work.

**Comment by Mikejo5000** [comment]
@WardenGnaw @leslierichardson95 Hopefully, we can get the PR moved to the private repo. Let me know if you need any assistance.

**Comment by WardenGnaw** [comment]
@Mikejo5000 Sorry for not updating this. I have ported the changes [here](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5844). Thanks for the help!

**Pull request closed without merging**
