### PR TITLE
fix: MD005/list-indent

### PR DESCRIPTION
**Pull request by nschonni**
Inconsistent indentation for list items at the same level

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @evanwindom, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@nschonni : Thanks for your contribution! The author, @sayedihashimi, has been notified to review your proposed change.

**Comment by nschonni** [comment]
Added in the "MD006/ul-start-left" since they're pretty related

**Comment by sayedihashimi** [comment]
The changes for the docs that I authored (the 3 VSMac ones) looks good. There’s a lot of other edits to files that I don’t own. Not sure who should review/sign off on the PR.

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @sayedihashimi, has been notified to review your proposed change.

**Comment by nschonni** [comment]
@sayedihashimi I think it is usually @gewarren that handles these cross area PRs

**Comment by PRMerger9** [comment]
@GitHubber17 : Thanks for your contribution! The author, @sayedihashimi, has been notified to review your proposed change.

**Pull request merged**
