### PR TITLE
Changes to Block 23 for VS WriteTheDocs 

### PR DESCRIPTION
**Pull request by athyunnath**
See #5664 for reference.

Changed instances of "click" to "select" and other such instances for Block 23 of VisualStudio Docs.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@athyunnath : Thanks for your contribution! The author(s) have been notified to review your proposed change. @evanwindom

**Comment by athyunnath** [comment]
Hello, 

Still working on this Draft Pull Request. Will click ready for review once it's done! 
In the meantime I am unable to add the label "Write the Docs 2020" to this PR. Could you add it or help me out on how to add it please?

**Comment by PRMerger13** [comment]
@athyunnath : Thanks for your contribution! The author(s) have been notified to review your proposed change. @evanwindom

**Comment by PRMerger19** [comment]
@athyunnath : Thanks for your contribution! The author(s) have been notified to review your proposed change. @evanwindom

**Comment by PRMerger15** [comment]
@tedhudek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @evanwindom

**Comment by PRMerger15** [comment]
@tedhudek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @evanwindom

**Comment by John-Hart** [comment]
@ghogen could you please do a quick review of this?

**Pull request merged**
