### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Ishmeet-Singh-Saggu**
A couple of minor changes

### CODE REVIEW

**Comment by PRMerger19** [comment]
@Ishmeet-Singh-Saggu : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@Mikejo5000 Can you take a look at these suggestions?

**Comment by Mikejo5000** [comment]
@Ishmeet-Singh-Saggu "Measure performance" would be OK as an alternative.

**Comment by PRMerger14** [comment]
@Ishmeet-Singh-Saggu : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by Ishmeet-Singh-Saggu** [comment]
Thanks for suggestion. I have made the required changes as specified, please review it.

**Comment by Ishmeet-Singh-Saggu** [comment]
Thanks for suggestion. I have made the required changes please review it.

Regards,
Ishmeet Singh Saggu

**Comment by tfosmark** [comment]
@Mikejo5000 Please review the changes and sign off if these are acceptable. Thank you!

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@Mikejo5000: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Mikejo5000** [comment]
@gewarren for sign-off

**Pull request merged**
