### PR TITLE
Fixed logo images reference

### PR DESCRIPTION
**Pull request by IrvinDominin**
Fixed logo images reference in the correct internal repo

### CODE REVIEW

**Comment by PRMerger16** [comment]
@IrvinDominin : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@gewarren - Would you review the proposed changes? Thanks

**Comment by gewarren** [comment]
@IrvinDominin Can you give some context on this? If you are a Microsoft employee, can you create the PR in the private repo, visualstudio-docs-pr, so we can see a preview build?

**Comment by IrvinDominin** [comment]
Hi @gewarren I'm not a Microsoft employee, I have simply found this issue on the docs so I tried to do my duty. I hope I'm following the rigth path.

**Comment by gewarren** [comment]
@IrvinDominin What was the impetus for the changes, then? The icons look correct to me on this page: https://docs.microsoft.com/en-us/visualstudio/?view=vs-2017#pivot=languages. @ghogen FYI

**Comment by ghogen** [comment]
The image paths currently used on this page are deliberately referencing the cross-site .svg files - that way if a language changes its logo, we can update it there instead of having a lot of different places where it needs to be updated.

**Comment by gewarren** [comment]
Closing this PR since we don't want to change the cross-site logo links at this point.

**Pull request closed without merging**
