### PR TITLE
Document additional entries in the CV_CFL_LANG enum

### PR DESCRIPTION
**Pull request by arlosi**
Several items were missing from the `CV_CFL_LANG` enum. This documents the latest set of values from `cvconst.h`

### CODE REVIEW

**Comment by PRMerger9** [comment]
@arlosi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Mikejo5000 — APPROVED** [review]

**Comment by Mikejo5000** [comment]
@arlosi Thanks! Sorry for the slow response here.

**Comment by arlosi** [comment]
@Mikejo5000 thanks for the review! Let me know if there's anything else I need to do to get this merged.

**Comment by Mikejo5000** [comment]
@arlosi No, it will get synced and then published this week. Thanks!

**Pull request merged**
