### PR TITLE
Update set-defaults-for-enterprise-deployments.md

### PR DESCRIPTION
**Pull request by edwardskrod**
The current text makes it look like the registry key path is:  Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\Setup\registry
This isn't correct.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@edwardskrod : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@anandmeg - Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger10** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by christineruana** [comment]
@anandmeg, I'm talking with @edwardskrod now.

**Comment by christineruana** [comment]
@anandmeg  - this change looks good to me.  We'll probably be making a few more additional changes to this space shortly.  
cc @edwardskrod .

**Comment by ghogen** [comment]
Closing and reopening to trigger build validation.

**Review by anandmeg — APPROVED** [review]
Thanks for the updates!

**Comment by anandmeg** [comment]
#sign-off

**Pull request merged**
