### PR TITLE
Fix the fileToFile sample

### PR DESCRIPTION
**Pull request by Tragetaschen**
My intuition at first thought the given description was the expected one, however as the screen shot shows, it's the other way around

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Tragetaschen : Thanks for your contribution! The author, @angelosp, has been notified to review your proposed change.

**Comment by Tragetaschen** [comment]
Hrmpf. I accidentally added a superfluous . in the GitHub editor...

**Comment by PRMerger12** [comment]
@Tragetaschen : Thanks for your contribution! The author, @angelosp, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@AngelosP Angelos, can you take a look at this PR please?

**Pull request merged**
