### PR TITLE
upgrade nuget and netcore versions in sample solution

### PR DESCRIPTION
**Pull request by jfleisher**
Feedback ticket from customer indicated that the sample solution here was not compatible with latest updates to VS2019 for live Unit Testing.

This PR updates the solution to latest versions and removes the problem encountered by the user.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1059211

### CODE REVIEW

**Comment by ktoliver** [comment]
closing/reopening to trigger automation

**Comment by ktoliver** [comment]
Hi @ghogen - The last writer to work with this content appears to be Ron Petrusha, who I am not finding as a current contributor. Could you review or assign for review? Thank you.

**Comment by ghogen** [comment]
@Mikejo5000 Is this in your area?

**Comment by Mikejo5000** [comment]
Yep, re-assigning

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@Mikejo5000: I'm sorry - only the author of this article, @jillre, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Thanks, reviewers.

**Pull request merged**
