### PR TITLE
Added ANCMPreConfiguredForIIS

### PR DESCRIPTION
**Pull request by jcoutch**
This change is to add `ANCMPreConfiguredForIIS` to the list of common MSBuild project properties, which was introduced in Visual Studio/MSBuild 16.3:
https://github.com/aspnet/websdk/issues/564#issuecomment-532900476

### CODE REVIEW

**Comment by PRMerger6** [comment]
@jcoutch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, should this property be documented here, since it is specific to IIS?

**Comment by rainersigwald** [comment]
@vijayrkn do you think this should be documented here? Is there a docs page with other ASP.NET-specific properties that would be a better home for it?

**Comment by vijayrkn** [comment]
A better place for this would be in the ASP.NET docs. @bradygaster - Do you know what would be a good place to get the ASP.NET IIS integration properties documented?

/cc @BillHiebert

**Comment by bradygaster** [comment]
I would initially say one of the articles below this one in our TOC on docs. https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-3.1

**Comment by ghogen** [comment]
Closing, per previous discussions.

**Pull request closed without merging**
