### PR TITLE
Fix API typo

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixing a typo in the navigation bar for updating an extension for VS 2022.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@MariaSolOs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Index File | This PR contains a change to the index file.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Index File | This PR contains a change to the index file.

**Comment by Court72** [comment]
@ankitvarmait, @ghogen  

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MariaSolOs** [comment]
Any updates on this? :)

**Comment by Court72** [comment]
@ankitvarmait, @ghogen

Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?

Thanks!

**Comment by MariaSolOs** [comment]
@Court72 Can someone else review this? It's been weeks now and it's a simple typo fix...

**Comment by Jak-MS** [comment]
@j-martens -  Can you review this PR?

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 Index File | This PR contains a change to the index file.

**Pull request merged**
