### PR TITLE
chore: Re-index git files for gitattributes

### PR DESCRIPTION
**Pull request by nschonni**
Looks like the `.gitattribute` file was added in https://github.com/MicrosoftDocs/visualstudio-docs/commit/d1d57cccc6addb866a93ad4dd3fc5402b4666c30.
This might be easier to do on the internal repo to avoid conflicts, so here are the steps if you want to do that:
- `git rm -rf --cached .`
- `git add .`
- `git commit -m "chore: Re-index git files for gitattributes"`

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@gewarren for input on this PR

**Comment by gewarren** [comment]
@nschonni Why is it necessary to reindex the files? If someone checks out one of these files, wouldn't the line endings be changed at that point?

**Comment by nschonni** [comment]
The problem that happens with the line ending/encoding issues is actually visible on this PR right now :wink: 
The "Conflicting files" and merge request flow does not work on these files that don't match the `.gitattributes`. Any bulk operation you do (EX: update metadata tags) will cause issues for any open PRs that touch those files.

Please don't merge this since it would likely break when you try to sync with the internal, but a one time pass will cleaner done from your private repo.

**Comment by gewarren** [comment]
@SyntaxC4 Can you review this public PR please? I don't have enough understanding to feel good about approving it. It's basically just running 'git rm -rf --cached .' on the repo.

(If you are okay with it, I'll do the steps in the private repo though, so please don't actually "Approve" it.)

**Comment by gewarren** [comment]
@SyntaxC4 Ping for your feedback on this PR please.

**Comment by nschonni** [comment]
FYI, this may be coming internally from the publishing people https://github.com/MicrosoftDocs/azure-docs/issues/14166#issuecomment-436080763

**Comment by gewarren** [comment]
@nschonni Thanks for doing this. We will normalize the line endings in the private repo, so I'm closing this out.

**Pull request closed without merging**
