### PR TITLE
Add link to CMake-specific debugging docs

### PR DESCRIPTION
**Pull request by esweet431**
CMake support leverages Open Folder but has some CMake-specific properties and behavior

### CODE REVIEW

**Comment by PRMerger15** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TerryGLee** [comment]
#sign-off

**Pull request merged**
