### PR TITLE
General formatting and MSBuild capitalization

### PR DESCRIPTION
**Pull request by gusper**

### CODE REVIEW

**Comment by gewarren** [comment]
@gusper thanks for your contribution. @Mikejo5000, the capitalization looks good. I'm not sure if we want to format some of the words as code though. I'll let you decide.

**Comment by gusper** [comment]
@gewarren makes sense. Let me know if there's any guidance on formatting you could point me to. Thanks!

**Comment by gewarren** [comment]
@gusper our style guide and contributor's guide do need to be updated (thanks for the reminder :) but there's a little bit of info about text styling [here](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/styleguide/template.md#text-styling).

**Comment by gusper** [comment]
@gewarren thanks for the link. I'll go through it before whatever my next PR ends up being. From a quick skim though, it doesn't look like it makes it clear yet which way to go with backticks within text blocks. When I initially submitted the changes, I was thinking it was more consistent (e.g., lines 81, 87 already had Directory.Build.props in backquotes, but line 57 didn't), but happy to edit it even if you all just want the capitalization parts.

**Comment by Mikejo5000** [comment]
@gusper @gewarren I used italics for filenames, paths, per style guide. The guidance has changed since these were last edited in depth, so the MSBuild docs are in need of a formatting scrub.

**Comment by gusper** [comment]
Just made one additional change as a backtick was missed when @Mikejo5000 switched to using italics.

**Pull request merged**
