### PR TITLE
-b argument missing in git-with-visual-studio.md

### PR DESCRIPTION
**Pull request by AndreKraemer**
The section "Create a new branch" contains the following code sample as the equivalent for creating a branch: `git checkout <branchname>`
This command however doesn't create a new branch, it's used to switch to an existing branch. In order to create a branch with the checkout command,
you have to pass the **-b** argument to it like this:
`git checkout -b <branchname>`
This commit fixes this code sample

### CODE REVIEW

**Comment by PRMerger17** [comment]
@AndreKraemer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TerryGLee — APPROVED** [review]

**Comment by TerryGLee** [comment]
@AndreKraemer Yes, great catch! We appreciate the PR, too. Thanks!

**Comment by TerryGLee** [comment]
#sign-off

**Comment by AndreKraemer** [comment]
> @AndreKraemer Yes, great catch! We appreciate the PR, too. Thanks!

You're welcome, and thanks for accepting and merging my PR. :-) Short question @TerryGLee : I noticed the missing -b originally at the German version of the `git-with-visual-studio.md` file. Will the change be transferred to the localized version automatically by some translation mechanism, or should I create a PR for the German version, too?

**Comment by TerryGLee** [comment]
@AndreKraemer The German version will be automatically changed by a translation mechanism, but there is a short lag between with the English version is updated and all the localized language versions are updated. But, no need to create a separate PR. :)

**Pull request merged**
