### PR TITLE
Update xaml-hot-reload.md

### PR DESCRIPTION
**Pull request by amunger**
fixing error table

### CODE REVIEW

**Comment by PRMerger12** [comment]
@amunger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by amunger** [comment]
@Mikejo5000 - Looks like I'm not authorized to actually do the merge.

**Comment by Mikejo5000** [comment]
@amunger No worries, it will get merged by the doc people. Thanks!

**Pull request merged**
