### PR TITLE
Update visio-object-model-overview.md

### PR DESCRIPTION
**Pull request by Surrogate-TM**
add graphical view Visio object model

### CODE REVIEW

**Comment by jborsecnik** [comment]
@John-Hart, 

Can you review the proposed changes? Note that if we add the image, it should be moved to the media file for the repo (and the link adjusted), as media used in the repo are supposed to be stored in the repo. Can you do that?

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged" 
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger14** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by John-Hart** [comment]
@jborsecnik, the document that is being linked to is not an official Microsoft document.  I don't think we should be including that file here or linking to it.

**Comment by jborsecnik** [comment]
> @jborsecnik, the document that is being linked to is not an official Microsoft document. I don't think we should be including that file here or linking to it.

Should we close this PR?

**Comment by Surrogate-TM** [comment]
Yes, this picture from SDK of Visio 2002 (at unofficial site).
At official MS documents for versions 2003 and 2007 we have broken pictures

Visio Object Model [Visio 2003 SDK Documentation] | Microsoft Docs<https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2003/aa175615(v=office.11)>
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2003/aa175615(v=office.11)>
Visio Object Model [Visio 2003 SDK Documentation]<https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2003/aa175615(v=office.11)>
docs.microsoft.com


Visio Object Model Reference [Visio 2007 SDK] | Microsoft Docs<https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/aa342179(v=office.12)>
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/aa342179(v=office.12)>
Visio Object Model Reference [Visio 2007 SDK]<https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/aa342179(v=office.12)>
docs.microsoft.com

Starting from version 2010 SDK does not contain MS Visio object model schema 🙁

Best regards, Alex
MVP<https://mvp.microsoft.com/en-us/PublicProfile/5002444?fullName=Alexandr%20Kuzin>
________________________________

**Comment by John-Hart** [comment]
@jborsecnik I don't know what the official policy is for linking to non MS content but I think we should not and we should  close this PR.
@Surrogate-TM  - I don't know if it's possible but If we were to get the pictures fixed in the older docs would that be sufficient?

**Comment by Surrogate-TM** [comment]
> @Surrogate-TM - I don't know if it's possible but If we were to get the pictures fixed in the older docs would that be sufficient?

@John-Hart, Better something than nothing :)

**Comment by Surrogate-TM** [comment]
@John-Hart,
Using web.archive.org, I found what the object models looked like in the official documentation earlier
[Visio Object Model [Visio 2003 SDK Documentation]](https://web.archive.org/web/20200722071833/https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2003/aa175615(v=office.11))
[Visio Object Model Reference](https://web.archive.org/web/20200720230535/https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/aa342179(v=office.12))

**Comment by Surrogate-TM** [comment]
@John-Hart ,
Official source where we can find this poster: In Document "Visio 2010 Developer Training 03 - Programming with the Visio Object Model.docx" from package [Download Microsoft Visio 2010 Developer Training from Official Microsoft Download Center](https://www.microsoft.com/en-my/download/details.aspx?id=27198) at page 54 smile. 
Can we use this source ?

<https://teams.microsoft.com/l/message/19:ef604666b3a24839a59a5a87fa325b78@thread.skype/1655548270070?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=f7dee2a6-83e0-4a5c-b3ce-b0b5d4ffc8cb&amp;parentMessageId=1654675109449&amp;teamName=Visio Partners&amp;channelName=Общий&amp;createdTime=1655548270070>

**Comment by ghogen** [comment]
Closing and reopening to trigger new build validation feature.

**Comment by Surrogate-TM** [comment]
>[Suggestion: external-image] 

[Direct link](https://pnl1-word-view.officeapps.live.com/wv/WordViewer/Document.pdf?WOPIsrc=http%3A%2F%2Fpnl1%2Dview%2Dwopi%2Ewopi%2Eonline%2Eoffice%2Enet%3A808%2Foh%2Fwopi%2Ffiles%2F%40%2FwFileId%3FwFileId%3Dhttps%253A%252F%252Fdownload%252Emicrosoft%252Ecom%253A443%252Fdownload%252FF%252F0%252F0%252FF00E7198%252DCD99%252D40A9%252DA3B0%252D48E2EE0EAB34%252FVisio%2525202010%252520Developer%252520Training%25252003%252520%252D%252520Programming%252520with%252520the%252520Visio%252520Object%252520Model%252Edocx&access_token=1&access_token_ttl=0&z=9aa5b7751896c6c98d5031db73b597ca5b392dc7eed59219b310dc3871989b8b&type=accesspdf&DataUrlEnabled=false#page=57) for image on MS resource

**Comment by Surrogate-TM** [comment]
whats going on ?

**Comment by ghogen** [comment]
@Surrogate-TM 
This has been moved into the private repo, where we can see the docs build and ensure everything is correct, and discuss any policy or copyright issues that might be relevant. Closing this as a public PR.

**Comment by Surrogate-TM** [comment]
Ok

**Pull request closed without merging**
