### PR TITLE
Typo Fix in Mac OS Installation Guide

### PR DESCRIPTION
**Pull request by remona-minett**
This fixes the issue mentioned in #4572 and replaces "High Sierra 10.12" with "Sierra 10.12".

### CODE REVIEW

**Comment by PRMerger6** [comment]
@remona-minett : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ghogen** [comment]
@jmatthiesen Does this change look ok?

**Comment by heiligerdankgesang** [comment]
@ghogen ^

**Comment by ktoliver** [comment]
@heiligerdankgesang - The PR has been updated. Could you review and add `#sign-off` if it looks good to merge? Thanks.

**Comment by heiligerdankgesang** [comment]
#sign-off

**Pull request merged**
