### PR TITLE
add some extra defaults to exec task

### LINKED ISSUE #752: Defaults are not specified for each optional parameter
Each optional parameter should specify what the default value is

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb479ee7-d34c-dd5d-6843-4abdec6c3894
* Version Independent ID: 40cd6644-b061-335e-7bd4-6beede753c5d
* Content: [Exec Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task)
* Content Source: [docs/msbuild/exec-task.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/exec-task.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #752

### CODE REVIEW

**Comment by PRMerger19** [comment]
@SimonCropp : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@SimonCropp : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@SimonCropp Looks good. Thanks!

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
