### PR TITLE
Fixes #1074 - updated vs-alternate-identity.md

### LINKED ISSUE #1074: Incorrect URL shown for Step 1 under "Add the Alternate Account"
Step 1 under "Add the Alternate Account" uses the wrong link. "Sign in to Visual Studio with your Microsoft account (https://{youraccount}.visualstudio.com)." 

Signing in with {youraccount}.visualstudio.com logs into a VSTS account, not a person's Visual Studio account. 

For people to be able to add an alternate account to their Visual Studio subscription, Step 1 should read "Sign in to your Visual Studio account using your Microsoft account (https://my.visualstudio.com)." (Or something to that effect.) 

At that point they can go into Subscriptions and add an alternate account. 

Step 5 has the correct URL to sign into a VSTS account, but the instruction should be worded differently. Current wording: "Use your work or school account to sign in to Visual Studio (https://{youraccount}.visualstudio.com)." More accurate wording: "Use your work or school account to sign in to Visual Studio Team Services (https://{youraccount}.visualstudio.com)."

-- Blizz 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e967e1-0b8e-a6b5-13ef-bd206ca6d13a
* Version Independent ID: 612623f5-6252-6353-8c7c-c1be43bd8801
* Content: [Identities for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-alternate-identity?toc=%2Fvsts%2Faccounts%2Ftoc.json&bc=%2Fvsts%2Faccounts%2Fbreadcrumb%2Ftoc.json&view=vsts)
* Content Source: [subscriptions/vs-alternate-identity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-alternate-identity.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

### PR DESCRIPTION
**Pull request by snowstormlife**
Corrected the wording for steps 1 and 5 and the URL reference for step 1 under the "Add an Alternate Account" heading. Current wording / reference isn't accurate.  --blizz

### CODE REVIEW

**Comment by PRMerger15** [comment]
@snowstormlife : Thanks for your contribution! The author, @evanwindom, has been notified to review your proposed change.

**Comment by snowstormlife** [comment]
Even better would be to use the exact same text for those steps in the FAQ, located here: https://www.visualstudio.com/my/myvsfaq#alternate

**Comment by TerryGLee** [comment]
@evanwindom If you approve of this PR, please add the text "# sign - off" to this topic. (Note that the text must appear altogether and not with the spaces that I included.)

**Comment by evanwindom** [comment]
#sign-off

**Comment by TerryGLee** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@TerryGLee: I'm sorry - only the author of this article, @evanwindom, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
