### PR TITLE
Update common-msbuild-project-properties.md

### PR DESCRIPTION
**Pull request by ocallesp**
Adding OutDir property for msbuild.
OutputPath is for legacy. We should use OutDir instead.
https://github.com/Microsoft/msbuild/issues/87

### CODE REVIEW

**Comment by PRMerger19** [comment]
@ocallesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ocallesp** [comment]
Adding this msbuild property in code 
PR
https://github.com/dotnet/project-system/pull/5773

**Comment by Chatina73** [comment]
What are my sources?

**Comment by ghogen** [comment]
It might not be as simple as recommending OutDir only - but it should definitely be added to the documented properties.
#sign-off

**Pull request merged**
