### PR TITLE
With VS 16.5 one of Known issues is fixed

### PR DESCRIPTION
**Pull request by DavidKarlas**
I'm not familiar with updating docs... Is there a way to ensure this is merged as soon as 16.5 hits stable, or do we just merge this now?

More info about fix: https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/214331

### CODE REVIEW

**Comment by PRMerger17** [comment]
@DavidKarlas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TerryGLee** [comment]
@DavidKarlas Thanks for your PR! Let's not publish this until 16.5 is GA, per https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019 
Meanwhile, there is an internal process on how to add this to a 16.5 release branch; I'll send you some information via email.

**Comment by TerryGLee** [comment]
#hold-off

**Comment by ktoliver** [comment]
Hi @terryglee - Is this PR in progress, or should it be closed now? Thanks.

**Comment by TerryGLee** [comment]
#sign-off

**Pull request merged**
