### PR TITLE
Update install-and-use-visual-studio-behind-a-firewall-or-proxy-serve…

### PR DESCRIPTION
**Pull request by olholder**
…r.md

added Visual Studio Search Service endpoint

### CODE REVIEW

**Comment by PRMerger10** [comment]
@olholder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@olholder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@olholder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ornellaalt** [comment]
#sign-off

**Review by ornellaalt — APPROVED** [review]

**Comment by PRMerger14** [comment]
@olholder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@olholder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ornellaalt — APPROVED** [review]

**Comment by ornellaalt** [comment]
#sign-off

**Comment by ornellaalt** [comment]
@ghogen can you please merge this?

**Review by ghogen — APPROVED** [review]

**Pull request merged**
