### PR TITLE
fix: MD023/heading-start-left/header-start-left

### PR DESCRIPTION
**Pull request by nschonni**
- Combined double Example headings in code quality docs
- Spaces around headers
- Leading spaces in lists
- Leading spaces in paragraphs
- Replace nested headers in lists with bold
- Remove incorrect code fence languges
- Trim trailing spaces

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @MikeJo5000, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're reviewing this pull request.

**Comment by Jak-MS** [comment]
@Mikejo5000 - can you take a look? we can move this to the private repo for staging and validation to verify that the changes render appropriately. however, we should only do that if you are on-board with the effort. (reference the conversation thread in this PR https://github.com/MicrosoftDocs/visualstudio-docs/pull/2753#issuecomment-467086467 ...

thanks.

**Comment by Mikejo5000** [comment]
@Jak-MS This looks OK to me; I don't see too much that needs to get viewed on stage.

**Comment by Jak-MS** [comment]
@Mikejo5000 - ok, sounds good. i reviewed the changes in GitHub view and seems to be okay.

**Pull request merged**
