### PR TITLE
Fix link for vs admin update enrollment

### PR DESCRIPTION
**Pull request by Applesauce314**
link on for "enroll their client machines into Visual Studio Administrator Updates was missing the domain"

### CODE REVIEW

**Comment by Court72** [comment]
@anandmeg 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by anandmeg — APPROVED** [review]
Thanks for fixing the link, @Applesauce314!

**Comment by anandmeg** [comment]
#sign-off

**Comment by anandmeg** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/issues/8685

**Pull request merged**
