### PR TITLE
Fixed the markdown for the VS2019 table

### PR DESCRIPTION
**Pull request by Dr-Scaffa**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Dr-Scaffa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ghogen** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@ghogen, I think this PR needs to be brought over to the private repo to check/correct staging. There appears to be a problem with the moniker-related text in the preview. The first sections looks ok, but the later info appears as an undifferentiated block of text. This clip shows part of the problem:

image

**Comment by PRMerger9** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@ghogen - i made some small edits to fix the tables. please take a look and sign off again if you approve. thanks.

**Comment by ghogen** [comment]
#sign-off
I will also check this when it merges to the private repo and we see a build.

**Pull request merged**
