### PR TITLE
clarifying why a user might need to obtain and build plugin from github

### PR DESCRIPTION
**Pull request by congruidavidli**

### CODE REVIEW

**Comment by congruidavidli** [comment]
Currently, there are in-product notifications that use the aka.ms/vsuemarketplace and aka.ms/vsuegithub links to direct users to install the plugin. Since we have built docs, the in-product links will now point to the docs. Consequently, we need new aka redirects in this doc to avoid circular dependencies. The new links still point to the same place.

Lastly, I added a clarification why someone may need to obtain the plugin from github

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Thank you for the updates.

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
