### PR TITLE
Add a Powershell alternative

### PR DESCRIPTION
**Pull request by Robertschv**
This is a PowerShell alternative for the people who want to use Only PowerShell when creating a Dockerfile.
This script I put here is a small version of the another one I have, so I haven't tested this small one yet. But it should work just fine.
It may need a bit of order too.

the issue I made before
#6486

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @Robertschv - Thank you for your contribution. Would you take a moment to sign the Contributor License Agreement (CLA)? After the CLA is signed, someone can review your pull request. Thanks!

**Comment by PRMerger14** [comment]
@Robertschv : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@ornellaalt Could you review the proposed update to your article? Thanks.

**Comment by ornellaalt** [comment]
Hi @Robertschv, thank you for your contribution. Your proposed changes show downloading a Build Tools bootstrapper from a specific release, instead of getting the latest like the other example on the page. We don't encourage users to download fixed versions in our documentation because they are likely to not contain security fixes that come out after the initial release.

**Comment by Robertschv** [comment]
Ok, I made the change to the patch, and now I am going to create another Pull request

**Pull request closed without merging**
