### PR TITLE
245493

### PR DESCRIPTION
**Pull request by v-savila**
removed duplication of "for Visual Studio" in line 34 for loc fix

### CODE REVIEW

**Comment by PRMerger16** [comment]
@v-savila : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by v-savila** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@v-savila: I'm sorry - only the author of this article, @mikejo5000, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
