### PR TITLE
missing from menu option

### PR DESCRIPTION
**Pull request by surlydev**
added "Project" into menu text (also ellipses ... at end due to it opening a dialog)

### CODE REVIEW

**Comment by PRMerger12** [comment]
@surlydev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TerryGLee** [comment]
@surlydev Thanks for your PR; we appreciate it. Please note that I must edit it somewhat. If you view the markup of the content, you might note sections that have monikers on them, such as `::: moniker range="vs-2017"` etc. What these do is make the content on a page work for the two most recent versions of the product, Visual Studio 2017 and Visual Studio 2019. The change you suggested is relevant only to Visual Studio 2019, so I must add the monikered markup so that the content can still serve two audiences. FYI.

**Review by TerryGLee — COMMENTED** [review]
Please note my previous comment.

**Review by TerryGLee — APPROVED** [review]
Approved the edits I made to account for monikered content that applies to both Visual Studio 2017 and Visual Studio 2019. (Note that monikerization works best when you repeat an entire procedure; enumeration can sometimes produce unexpected results when you try to moniker a single step.)

However, @surlydev, it looks like you might have to re-sign the CLA before we can process the change and then the PR.

**Comment by ktoliver** [comment]
@surlydev - Thank you for your contribution. Would you take a moment to sign the Contributor License Agreement (CLA)? After the CLA is signed, we can merge the pull request. Thanks!

**Comment by PRMerger19** [comment]
@TerryGLee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TerryGLee** [comment]
#sign-off

**Comment by surlydev** [comment]
@TerryGLee thank you for completing the editing with the additional moniker information, I wasn't fully aware, and will bear this in mind for future.

**Pull request merged**
