### PR TITLE
AddDeleteInputFile

### PR DESCRIPTION
**Pull request by shahabhijeet**
Adding a note for scenario when adding new files or deleting existing files does not update output.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@shahabhijeet : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ghogen** [comment]
@shahabhijeet @rainersigwald 
Let's close this one, but internally we will add a Note.  I think the wording has to very clear.

**Comment by ghogen** [comment]
Closing - thanks for pointing out this issue @shahabhijeet

**Comment by shahabhijeet** [comment]
Would you tell me what you mean by "internally we will add a Note", does that mean that note will not be reflected on the public docs?

**Pull request closed without merging**
