### PR TITLE
Replace placeholder variable with actual variable

### LINKED ISSUE #2251: inconsistent use of "<userpath>" in sample code
In the first sample that mentions `<userpath>` there is an extra paren after the `>`

`await textService.WriteLineAsync(<userpath>), "this is a test");`

I recommend making this a real variable and either leave it uninitialized or init it with a path that will fail.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4999b84e-a7f2-1ffc-6d02-d439ff0330de
* Version Independent ID: 7755af16-b4f5-e3b8-798f-35ea143ad306
* Content: [How to: Provide an Asynchronous Visual Studio Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-provide-an-asynchronous-visual-studio-service?view=vs-2017)
* Content Source: [docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

### PR DESCRIPTION
**Pull request by lennartb-**
Fixes #2251. I hope the sample file and path is all right, I got it from the System.IO.Directory docs.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@lennartb- : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by gregvanl** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@gregvanl: I'm sorry - only the author of this article, @madskristensen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by gregvanl** [comment]
@madskristensen After you approve at PR, you can add the comment `#sign-off` and PRMerger will move the PR to 'ready to merge'. I no longer have that "power".

**Comment by madskristensen** [comment]
#sign-off

**Pull request merged**
