### PR TITLE
Update specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md

### PR DESCRIPTION
**Pull request by cshah-mn**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@cshah-mn : Thanks for your contribution! The author, @"mikejo5000", has been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@cshah-mn Thanks for the fix!

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@Mikejo5000: I'm sorry - only the author of this article, @"mikejo5000", can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Mikejo5000** [comment]
@gewarren Thanks! Just about to tell you here...

**Pull request merged**
