### PR TITLE
Update uninstall-visual-studio.md

### PR DESCRIPTION
**Pull request by Orange23333**
The original text `17 versioned products` will be translated to `17 个版本控制的产品`(means `17 version controlled products`) in Chinese. As you can see, translator sensed `17` as an amount here. So use `products of version 17` may guide translator makes right translation result.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Orange23333 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Orange23333** [comment]
Okay, thank you for your reminder.
#sign-off

**Comment by PRMerger8** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @anandmeg

**Comment by Orange23333** [comment]
Oh sorry, it's me use a sign-off command . I misunderstood the conversation whom you was talking to.

**Review by anandmeg — APPROVED** [review]
Thanks for the update, @Orange23333!

**Comment by anandmeg** [comment]
#sign-off

**Comment by samochod23** [comment]
Plisę seve Comixs .#SEVE.COM NORDIN.COM

**Pull request merged**
