### PR TITLE
Update the list of domains that should be whitelisted

### PR DESCRIPTION
**Pull request by keithrob**
Update the list of domainsthat should be whitelisted.

### CODE REVIEW

**Comment by TerryGLee** [comment]
@keithrob This is in tech review; FYI.

**Comment by keithrob** [comment]
@TerryGLee  & @ikeras ,
Can you approve so that this can be merged?

**Comment by TerryGLee** [comment]
@ikeras Thanks, Anson.

**Comment by TerryGLee** [comment]
#sign-off

**Pull request merged**
