### PR TITLE
Adding notes and links to Office Add-ins documentation

### PR DESCRIPTION
**Pull request by mscharlock**
This PR adds a note that links to Office Add-ins docs, which should help people discover them if they want to learn about a newer option for Office extensibility. 
Let me know if you have any questions. Unfortunately I will be going on medical leave soon but you can also email @davidchesnut or @Reezaali with questions. Thanks!

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @mscharlock 

Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules. 

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 

For more information, see [Should I work in a private or a public repo?](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) 

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

Would you create a pull request in the private repo to make these updates? We'll close this PR. Thank you.

**Comment by ktoliver** [comment]
cc @gewarren @ghogen

**Comment by mscharlock** [comment]
So you need to approve me as a contributor or something to this repo in order for me to push to the private repo. Otherwise, I have to fork like I've done here. Also in the forked situation, I can't see the validation problems, because I can't see the build report. Can this get done ASAP? I apologize for the urgency but I am going on medical leave as of tomorrow. Happy to chat more via email.

**Comment by ktoliver** [comment]
@mscharlock @gewarren @ghogen We're in the process of moving this commit to the private repo. I'll post information about the new PR here when the PR has been created. Then, we'll close this PR.

**Comment by gewarren** [comment]
> So you need to approve me as a contributor or something to this repo in order for me to push to the private repo. Otherwise, I have to fork like I've done here. Also in the forked situation, I can't see the validation problems, because I can't see the build report. Can this get done ASAP? I apologize for the urgency but I am going on medical leave as of tomorrow. Happy to chat more via email.

Yes you'll need to work in a fork of the private repo; we all do. Can you elaborate on why you can't see the validation problems in a fork? The PR will have a link to the build report.

**Comment by mscharlock** [comment]
Yeah as a forked contributor all you see is "Merging is blocked, the base branch restricts merging to authorized users" and you don't get a build report.

**Comment by gewarren** [comment]
> Yeah as a forked contributor all you see is "Merging is blocked, the base branch restricts merging to authorized users" and you don't get a build report. What you do see is that CLA requirements are met or not, but it doesn't tell you about the actual issues in the PR if there are any.

There is no build validation in the public repo. You'll get it in the private repo, which is why we ask MS folks to use the private repo.

**Comment by ktoliver** [comment]
Private repo PR #https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5211 replaces this PR. After we get a successful build in the new PR, we can close this PR.

**Comment by Jak-MS** [comment]
this was recreated by @ghogen in the private repo https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5215

**Pull request closed without merging**
