### PR TITLE
chore: Add currenlty passing Markdownlint config

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @brickgeorge, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @gewarren @ghogen - Would you review the proposed config file addition? Thanks.

**Comment by gewarren** [comment]
@SyntaxC4 Could you review this please? Do you have this in other repos?

**Comment by ktoliver** [comment]
Related PR: https://github.com/MicrosoftDocs/azure-docs/pull/25729

**Comment by gewarren** [comment]
[.NET added this fil]e(https://github.com/dotnet/docs/pull/10764), so I think it's okay to add here too.

**Pull request merged**
