### PR TITLE
Updated 'Sync' description.

### PR DESCRIPTION
**Pull request by Chiramisu**
Pull then Push are sequential operations, not simultaneous.

### CODE REVIEW

**Comment by Chiramisu** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@TerryGLee, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TerryGLee** [comment]
@Chiramisu I'll do so soon; thanks for the PR!

**Comment by TerryGLee** [comment]
#sign-off

**Review by TerryGLee — APPROVED** [review]

**Pull request merged**
