### PR TITLE
Including CodeCracker

### PR DESCRIPTION
**Pull request by carloscds**
include CodeCracker analyser.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@carloscds : Thanks for your contribution! The author, @kuhlenh, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@kendrahavens @mavasani Is this okay to include?

**Comment by kendrahavens** [comment]
Hi @carloscds, could you give a brief description of why this change should be included here? Forgive me, I'm not too familiar with the CodeCracker project. There are many analyzer packs in the ecosystem that we *could* link to in our docs, but I don't think the docs are the best discoverability mechanism for the hundreds of options out there.

@jinujoseph @sharwell In case, you have input on this as well.

**Comment by carloscds** [comment]
@kendrahavens CodeCracker it's one of fist project about Roslyn Anayzers. Microsoft already use it in many events and @sharwell know this project. You can seek more about at https://github.com/code-cracker/code-cracker

**Comment by kendrahavens** [comment]
Thanks @carloscds. We can add it then! 

My minor concern was this doc could become overloaded with external links and make discovering the built-in tools (the main purpose of docs.microsoft.com) more difficult. That's definitely not a worry at this stage so we can add the link you suggest.

**Comment by carloscds** [comment]
@kendrahavens Thanks, for me CodeCracker is the same of StyleCopAnalyzers, for example.

**Comment by sharwell** [comment]
@carloscds Yep that was my view as well

**Pull request merged**
