### PR TITLE
Description added for C# option "Don't put ref or out on custom struct"

### LINKED ISSUE #8553: What does Visual Studio C# option "don't put ref or out on custom struct" do?
The below mentioned documentation page doesn't explain what the C# text editor Advanced option "don't put ref or out on custom struct" does, i.e. what different output it generates:

Extract Method

Any detailed information on this would be particularly useful when running a localized Visual Studio application. The translated option text in the VS application doesn't get clear on what this option does.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f41602f7-2c5e-bf2a-9eab-50740dd10784
* Version Independent ID: c6b1f7c4-eb2d-a62a-7e1b-eb32b8a88947
* Content: [Options, Text Editor, C#, Advanced - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.CSharp.Advanced)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-csharp-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-csharp-advanced.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

### PR DESCRIPTION
**Pull request by SetTrend**
Fixes #8553

### CODE REVIEW

**Comment by Court72** [comment]
@mikadumont 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by SSBatalian — CHANGES_REQUESTED** [review]
// Version information for an assembly consists of the following four values:
// Major Version
// Minor Version
// Build Number
// Revision
[assembly: AssemblyVersion("1.0.0.0")]  
[assembly: AssemblyFileVersion("1.0.0.0")]

**Comment by ghogen** [comment]
@jmarolf can you review?

**Review by jmarolf — APPROVED** [review]

**Comment by ghogen** [comment]
#sign-off

**Pull request merged**
