### PR TITLE
Update live-unit-testing-faq.md

### PR DESCRIPTION
**Pull request by morrisjoe**
Starting an empty PR to facilitate review comments and updates.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/test/live-unit-testing-faq.md](https://github.com/morrisjoe/visualstudio-docs/blob/patch-7/docs/test/live-unit-testing-faq.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C15%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708152216179398-239%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jimmy9988** [comment]
@morrisjoe 
Two opinions come to me.

1. As we will remove the "Reset clean" menu item in 15.4 preview 2, it might be better for us to decrease the possibility that user use it or even get addicted to it. Maybe consider not mention the addition of "Reset clean" in the menu bar but tell user to delete the persisted data from the options/Live Unit Testing.
2. Consider mentioning that manually modifying the csproj by changing, adding and removing TFM when LUT is on might introduce inconsistence and instability. The fix now is deleting the .VS folder or using the delete persisted data bottom to delete the lut folder. Users might fall into these issues, as we highlight that LUT supported .NET core now and there are still pending issues (like https://github.com/dotnet/testimpact/issues/2032) on project system and our side,

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/test/live-unit-testing-faq.md](https://github.com/morrisjoe/visualstudio-docs/blob/patch-7/docs/test/live-unit-testing-faq.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C16%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708162240289318-239%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ghogen** [comment]
@rpetrusha can you review please?

**Comment by rpetrusha** [comment]
@morrisjoe, is this ready to merge?

**Pull request merged**
