### PR TITLE
Update isolating-code-under-test-with-microsoft-fakes.md

### PR DESCRIPTION
**Pull request by jVanZwieten**
erroneously mentions shims in the stubs section, probably copypasta

### CODE REVIEW

**Comment by jVanZwieten** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
@Mikejo5000 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by Mikejo5000 — APPROVED** [review]
@jVanZwieten Thanks!

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
