### PR TITLE
Add link to recommended MSBuild Properties

### PR DESCRIPTION
**Pull request by vritant24**
.`runsettings` File paths can be specified with an MSBuild property, but only the ones mentioned in the linked doc work in all cases.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@vritant24 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@vritant24 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @Mikejo5000 - If the updates are approved, we can remove the locale from the URL before merging the PR.

**Comment by Mikejo5000** [comment]
@ktoliver That would be great if you can fix the URL. Let me know if you want me to sign off.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @Mikejo5000 

I'll go ahead and merge the PR.

**Comment by vritant24** [comment]
Thanks for fixing the URL and the quick merge @ktoliver @Mikejo5000 💯

**Pull request merged**
