### PR TITLE
Fix typo - VB should be C#

### PR DESCRIPTION
**Pull request by GregTrevellick**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@GregTrevellick : Thanks for your contribution! The author, @gregvanl, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author, @gregvanl, has been notified to review your proposed change.

**Comment by gregvanl** [comment]
Hi @GregTrevellick, looks like @ktoliver beat you to it :-).
Thanks again for your PR.
#sign-off

**Comment by Tomas2046** [comment]
#1842

**Comment by Tomas2046** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/commit/59180b08450e8dbaa267a19ec6490f7daf15bdc59180b0

**Pull request merged**
