### PR TITLE
Visual Studio Tools for Unity - Changelog fix

### PR DESCRIPTION
**Pull request by sailro**
Add missing newlines
Version number standardization
Fix release dates

### CODE REVIEW

**Comment by sailro** [comment]
cc @gregvanl

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cross-platform/change-log-visual-studio-tools-for-unity.md](https://github.com/sailro/visualstudio-docs/blob/patch-4/docs/cross-platform/change-log-visual-studio-tools-for-unity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C11%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201708111631432216-230%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sailro** [comment]
@gregvanl, the current online page does not include those latest updates. (I tried to cleam my caches, use another browser/PC so it is not a cache issue).

How could we fix this ?

**Comment by gregvanl** [comment]
The new PR flow doesn't go live on merge. It now goes to a private branch for final review and publishing. We just merged that branch this morning so you should now see your changes live. 
Publishing to live was delayed for the 15.3 release today but normally should be within a day of merging a PR.

**Comment by sailro** [comment]
Ok understood. Thanks.

**Pull request merged**
