### PR TITLE
Improve working-with-c-cpp-python-in-visual-studio.md

### PR DESCRIPTION
**Pull request by shreyanavigyan**
The `working-with-c-cpp-python-in-visual-studio` docs states that we have to use the property **General** -> **General** -> **Target Extension** to set the file extension to `.pyd`. But in Visual Studio 2019 we have to use the property  **General** -> **Advanced** -> **Target File Extension** to set the file extension to `.pyd`. This PR just updates that.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@shreyanavigyan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shreyanavigyan** [comment]
Ping

**Comment by JoshuaPartlow** [comment]
Hi @shreyanavigyan - Thanks for creating a PR to update the docs. Since our content is single sourced, we need to also maintain the VS 2017 information. I added a commit to handle that through our versioning mechanism, but your change should remain for VS 2019.

**Review by JoshuaPartlow — APPROVED** [review]

**Comment by PRMerger20** [comment]
@JoshuaPartlow : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JoshuaPartlow** [comment]
#sign-off

**Pull request merged**
