### PR TITLE
chore: Add code fence languages to scripting-docs

### PR DESCRIPTION
**Pull request by nschonni**
Sorry this is kind of noisy, it was mostly scoped find/replace after looking at some of the sample code fences that were missing the languages, then doing find/replace in VS code.
I believe some of the changed lines where from mixed line endings in some of the files that weren't normalized after the .gitattribues file got added to the repo

### CODE REVIEW

**Comment by Jak-MS** [comment]
@gewarren - I assigned this to you as a primary contributor. Might consider moving the commits from @nschonni  to the private repo so that you can take advantage of the validation and staging tools there.

**Comment by gewarren** [comment]
I'm going to let @Mikejo5000 look at this one.

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by Tomas2046** [comment]
Next

**Comment by ktoliver** [comment]
#hold-off  

The content team (@gewarren, @Mikejo5000) will move this commit to the private repository for validation and staging. Then, they'll close this PR.

**Comment by Mikejo5000** [comment]
Moved to MicrosoftDocs/visualstudio-docs-pr#3617

**Pull request closed without merging**
