### PR TITLE
[Unity] Troubleshooting and Known Issues typos

### PR DESCRIPTION
**Pull request by sailro**

### CODE REVIEW

**Comment by sailro** [comment]
cc @jbevain  @TerryGLee

**Comment by gewarren** [comment]
Should @conceptdev look at this?

**Comment by conceptdev** [comment]
thanks @gewarren taking a look. need to verify the suggested troubleshooting tip about the unity process.

**Comment by sailro** [comment]
This  addition is legit, and comes from a discussion I had with one of our user:
https://marketplace.visualstudio.com/items?itemName=SebastienLebreton.VisualStudio2015ToolsforUnity#qna

On a side note, I think I know what I am doing 'technically', given I wrote the product with @jbevain.

Thanks!

**Comment by conceptdev** [comment]
ha! sorry, i didn't even look at the provenance. lgtm then 😉

**Comment by sailro** [comment]
Thanks 👍

**Pull request merged**
