### PR TITLE
Adding exit command to the install script

### PR DESCRIPTION
**Pull request by milarso81**
Docker setup will get stuck if there is not exit at the end of the install script.
Adding exit command at the end of the script so that the example can work correctly. There are several issues logged because of this.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@milarso81 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@milarso81 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@milarso81 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@milarso81 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@milarso81 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@milarso81 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@milarso81 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by j-martens** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@j-martens: I'm sorry - only the author of this article, @anandmeg, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by anandmeg** [comment]
@milarso81, thanks for the fixes!
#sign-off

**Pull request merged**
