### PR TITLE
Document WriteOnlyWhenDifferent parameter

### PR DESCRIPTION
**Pull request by geeeyetee**
Added `WriteOnlyWhenDifferent` parameter of `WriteLinestoFile` task, using verbatim Description from https://github.com/Microsoft/msbuild/blob/master/src/Tasks/FileIO/WriteLinesToFile.cs#L42-L44

### CODE REVIEW

**Comment by PRMerger6** [comment]
@geeeyetee : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@Mikejo5000 Can you take a look?

**Comment by Mikejo5000** [comment]
@geeeyetee Thanks for fixing this!

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
