### PR TITLE
H2 heading update - ADO #171906

### PR DESCRIPTION
**Pull request by damabe**
Update articles to conform to Patterns guidance.

### CODE REVIEW

**Comment by damabe** [comment]
@j-martens and @anandmeg - This PR is ready for approval/merge.

**Comment by ShannonLeavitt** [comment]
@damabe - This PR is in the public repo. Did you intend to make this change in the private repo instead?

@anandmeg @j-martens - If you want to accept these changes in the public repo, please add a sign off. 

#label:"aq-pr-triaged"

**Comment by v-emilypr** [comment]
#please-close

**Comment by j-martens** [comment]
@v-emilypr  @damabe - is there another PR for us to look at instead?

**Pull request closed without merging**
