### PR TITLE
Updated quickstarts and tutorials for Visual Studio publish to match the UX in Visual Studio 16.6 (most recent stable release)

### PR DESCRIPTION
**Pull request by AngelosP**
Issue #5308 
Issue #5309 
Issue #5310 
Issue #5311
Issue #5312
Issue #5313
Issue #5314
Issue #5315

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @Angelosp - Contributors who work in the Product Manager role should work in the private repository for advanced quality validations and staging. Updates this extensive especially are best made in the private repository, where you can check everything on staging before merging.

Would you move these updates to a PR in the private repo? 

@Mikejo5000 for input or review.

**Comment by AngelosP** [comment]
I am somewhat confused. The instructions say to fork the repo, make changes and submit a PR. Is that not what I did? Or did I follow the wrong instructions?

**Comment by ktoliver** [comment]
Hi @angelosp - 

This content has a public repository, where Microsoft-external contributors may submit requests to update the documentation, and it has a private repository for Microsoft-internal contributors. The two repos are synced daily--the master version that is used to publish to live is in the private repo. 

It looks like you forked the public repo, [visualstudio-docs](https://github.com/MicrosoftDocs/visualstudio-docs). What would be best is to fork the private repo, [visualstudio-docs-pr](https://github.com/MicrosoftDocs/visualstudio-docs-pr).

This article in the Microsoft Docs contributor guide (CG) talks about public vs. private repos: [Should I work in a private or a public repository?](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master)

Also, be sure that you create a **working branch** when you first start to make updates that will go into a pull request. Don't work directly in master. See [Create a branch](https://review.docs.microsoft.com/help/contribute/edit-doc-with-vs-code-and-git-cli?branch=master#create-a-branch) in the CG.

If you need more assistance, send me email or contact me on Teams and I can point you to a Teams channel that provides Docs support. Thanks!

**Comment by AngelosP** [comment]
Thank you for taking the time to explain!

**Pull request closed without merging**
