### PR TITLE
Fix creating-an-extension-with-a-menu-command.md

### PR DESCRIPTION
**Pull request by briuk**
- Fix typos.

- Fix name of command callback function: current template of the custom command item adds handler named Execute.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@briuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@acangialosi Would you review the proposed update to your article? Thanks.

**Comment by leslierichardson95** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@leslierichardson95: I'm sorry - only the author of this article, @acangialosi, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
