### PR TITLE
Update stop-statements-in-visual-basic.md

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Youssef1313 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Youssef1313 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Youssef1313 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
