### PR TITLE
Fix description for NeverLockTypeAssemblies

### PR DESCRIPTION
**Pull request by dmetzgar**
Pulled description from https://msdn.microsoft.com/en-us/library/microsoft.build.tasks.generateresource.neverlocktypeassemblies.aspx

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/msbuild/generateresource-task.md](https://github.com/dmetzgar/visualstudio-docs/blob/patch-1/docs/msbuild/generateresource-task.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C16%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201707162200584947-189%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/msbuild/generateresource-task.md](https://github.com/dmetzgar/visualstudio-docs/blob/patch-1/docs/msbuild/generateresource-task.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C26%5C692e8138-f1b0-9929-d89e-225d116f9c25%5CPullRequest%5C201707261728354111-189%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dmetzgar** [comment]
Good catch! Removed the locale.

**Comment by kraigb** [comment]
That's why we actually do review PRs. :)

**Pull request merged**
