### PR TITLE
Update developer-community-privacy.md

### PR DESCRIPTION
**Pull request by jasonchlus**

### CODE REVIEW

**Comment by jasonchlus** [comment]
@ghogen please let me know if you have any questions/concerns with this update.

**Comment by ttorble** [comment]
@anandmeg 

Can you review the proposed changes?

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by anandmeg — APPROVED** [review]
Thanks @jasonchlus

**Comment by anandmeg** [comment]
#sign-off

**Pull request merged**
