### PR TITLE
added documentation for TestCaseFilter

### PR DESCRIPTION
**Pull request by ffMathy**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@ffMathy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
@pavelhorak @AbhitejJohn to check fix

**Comment by pavelhorak** [comment]
I believe is correct. @nohwnd can you confirm? Would it make sense adding TestCaseFilter attribute into [RunConfiguration element](https://github.com/MicrosoftDocs/visualstudio-docs/blob/aeb1d05603aab7f2417ac884d8a0e1959c0160bc/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md#runconfiguration-element) example?

**Comment by ffMathy** [comment]
See this. That's when it was merged. 

https://github.com/microsoft/vstest/pull/2356

**Comment by ffMathy** [comment]
It looks like it was undocumented on purpose according to #2356. However, I think it's a great feature and workaround for the issue here: https://github.com/microsoft/vstest/issues/2625

**Comment by nohwnd** [comment]
Yup, undocumented on purpose.

**Comment by Mikejo5000** [comment]
@nohwnd Closing based on preceding comments. Let me know if I missed something. Thanks!

**Pull request closed without merging**
