### PR TITLE
Updating Python Workload installation links for 2010, 2012, 2013

### PR DESCRIPTION
**Pull request by RaymonGulati1**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@RaymonGulati1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by RaymonGulati1** [comment]
Is there any way to "preview" the changes on a webpage before the PR is merged?

**Comment by JoshuaPartlow** [comment]
@RaymonGulati1 - The change looks fine to me. Were you ready for it to be merged or were you still making changes on the PR?

**Comment by RaymonGulati1** [comment]
Ready for merge

**Comment by JoshuaPartlow** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@RaymonGulati1 
> Is there any way to "preview" the changes on a webpage before the PR is merged?

If you use the private repo to submit your commits, you can use the staging, validation, and proofing tools there. As an FTE, you might be able to get private repo access. Here's some info:

> If you need help getting set up to work in the private repo, see [How to get to the private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master#how-to-get-to-the-private-repo). You can also take a look at the [GitHub account setup page](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master) for additional details on making sure you're set up.

**Comment by Jak-MS** [comment]
as @JoshuaPartlow mentioned, it's not necessary for this PR however.

**Pull request merged**
