### PR TITLE
can not watch video

### PR DESCRIPTION
**Pull request by fenneishi**
can not watch the video(https://youtu.be/Aq8eqApnugM)

### CODE REVIEW

**Comment by PRMerger3** [comment]
@fenneishi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by musliadi426** [comment]
Main2 yach😁

Sent from Yahoo Mail on Android 
 
  On Kam, Feb 3, 2022 at 11:46, ***@***.***> wrote:   
can not watch the video(https://youtu.be/Aq8eqApnugM)

You can view, comment on, or merge this pull request online at:

  https://github.com/MicrosoftDocs/visualstudio-docs/pull/7622

Commit Summary
   
   - 16c7f0c can not watch video

File Changes 
 
(1 file)
   
   -  M docs/python/managing-python-projects-in-visual-studio.md (2) 

Patch Links:
   
   - https://github.com/MicrosoftDocs/visualstudio-docs/pull/7622.patch
   - https://github.com/MicrosoftDocs/visualstudio-docs/pull/7622.diff

**Comment by ktoliver** [comment]
This pull request can't be merged in; it reports an issue. #hold-off 

@rjmolyneaux @ghogen The YouTube video in the link is set to private. Could you look into either changing the video permissions or replacing or removing the link to the video? Thanks.

image

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by rjmolyneaux** [comment]
Hi @fenneishi, 

We appreciate you bringing this to our attention. Your contribution helps us to both improve and maintain the efficiency of Microsoft documentation. You'll be able to see the updates made to this document shortly!

**Review by rjmolyneaux — COMMENTED** [review]
Hi @fenneishi,

We appreciate you bringing this to our attention. Your contribution helps us to both improve and maintain the efficiency of Microsoft documentation. You'll be able to see the updates made to this document shortly!

**Comment by ktoliver** [comment]
Hi @rjmolyneaux - This pull request can't be merged in; it reports an issue. 

The YouTube video in the link is set to private. 

_Action needed_: Could you look into either changing the video permissions or replace or remove the link to the video?

**Comment by rjmolyneaux** [comment]
Hi @ktoliver!
This PR has been resolved with [PR #9534](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9534/).

**Comment by ktoliver** [comment]
Thanks, all. #please-close

**Comment by musliadi426** [comment]
otvori vidi ima li dogovora molim blasah #japanese 🏴
Sukai kami di Facebook
--
Dikirim dari myMail untuk Android

**Pull request closed without merging**
