### PR TITLE
Add documentation for unit testing in other scenarios

### PR DESCRIPTION
**Pull request by paulvanbrenk**
This adds documentation on unit testing in the Open Folder scenario, and
for project types other than node.js project. (e.g. ASP.NET)

### CODE REVIEW

**Comment by PRMerger8** [comment]
@paulvanbrenk : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@paulvanbrenk : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@paulvanbrenk : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@paulvanbrenk : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by paulvanbrenk** [comment]
Thanks @Mikejo5000 , I think we should wait on @billti before actually merging

**Comment by Mikejo5000** [comment]
#hold-off

**Comment by Mikejo5000** [comment]
Thanks, I put a hold on it.

**Comment by Mikejo5000** [comment]
@paulvanbrenk These features are available in 15.8 Preview 3? There should be a note to that effect, which we can edit later for updates (like 15.8 RTW).

**Comment by paulvanbrenk** [comment]
@Mikejo5000 I believe so, they are there in the current preview for sure.

**Comment by gewarren** [comment]
@paulvanbrenk @Mikejo5000 This has been sitting for a while. 15.8 released yesterday - should we add a note in the topic about availability and then merge this PR?

**Comment by Mikejo5000** [comment]
@billti Bill, can we move this forward yet?

**Comment by billti** [comment]
Looks good. Let me just make sure we walk through the docs and test the scenarios to make sure steps match what finally shipped. Will circle back shortly...

**Comment by ktoliver** [comment]
@billti - Would you review the proposed changes? Thanks.

**Comment by billti** [comment]
@armanio123 Would you be able to verify these docs match the experience in 15.8 and sign-off on the docs being merged? Thanks.

**Comment by armanio123** [comment]
The docs matches with the experience on 15.8 (I tested on my local box using 15.8.2)

**Pull request merged**
