### PR TITLE
Update  adding-a-submenu-to-a-menu.md

### PR DESCRIPTION
**Pull request by Asugakoisi**
I changed some code, because I got `System.InvalidCastException` error and `VSTHRD010` warning when I ran the code of this tutorial.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Asugakoisi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@acangialosi 

Could you review the proposed changes to your article?

Thanks!

**Comment by leslierichardson95** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@leslierichardson95: I'm sorry - only the author of this article, @acangialosi, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
