### PR TITLE
Improve input validation message

### PR DESCRIPTION
**Pull request by cmkaya**
Replaces "integer" with "numeric" in the input validation prompt for user clarity after the decimal functionality.

### CODE REVIEW

**Comment by cmkaya** [comment]
@microsoft-github-policy-service rerun

**Comment by cmkaya** [comment]
@microsoft-github-policy-service agree

**Comment by ShannonLeavitt** [comment]
@anandmeg

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by anandmeg** [comment]
#sign-off

**Pull request merged**
