### PR TITLE
Added new data for IEnumerable visualizer,

### PR DESCRIPTION
**Pull request by hharshada**
changed the IEnumerable Table visualizer to just IEnumerable visualizer

### CODE REVIEW

**Comment by PRMerger14** [comment]
@hharshada : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@hharshada @Mikejo5000 - alternatively you can move these commits to the private repo.

Let us know if you need assistance.

**Comment by Mikejo5000** [comment]
@hharshada Harshada, if you are using VS for git work, here are the docs for that:
https://docs.microsoft.com/en-us/visualstudio/version-control/git-clone-repository?view=vs-2022
If it's helpful, I could port the PR, but I wanted you to receive contributor credit in the VS monthly reports.

**Comment by Jak-MS** [comment]
@hharshada @Mikejo5000 - if you've made these changes in the private repo, please link back to this PR (for completeness purposes).   Thanks.

**Pull request closed without merging**
