### PR TITLE
Update tutorial-projects-solutions.md

### PR DESCRIPTION
**Pull request by surlydev**
Menu is not nested.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@surlydev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TerryGLee — CHANGES_REQUESTED** [review]
As I noted in your previous PR, #6071, we must use monikered markup that allows us to provide instructions that are relevant for both Visual Studio 2017 _and_ Visual Studio 2019.

Please change your PR to the following, and then we'll accept it:

`::: moniker range="vs-2017"

If you want to check that your unit test is working, choose **Test** > **Run** > **All Tests** from the menu bar. A window called **Test Explorer** opens, and you should see that the **TestGetCurrentDate** test passes.

::: moniker-end

::: moniker range="vs-2019"

If you want to check that your unit test is working, choose **Test** > **Run All Tests** from the menu bar. A window called **Test Explorer** opens, and you should see that the **TestGetCurrentDate** test passes.

::: moniker-end`

**Comment by TerryGLee** [comment]
@surlydev For some reason, I was unable to edit this PR for you. I have included suggested edits in my previous comment; if you could apply those as a new commit to this PR, we can get this processed, too.

**Comment by PRMerger18** [comment]
@surlydev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by surlydev** [comment]
Hi @TerryGLee I've updated the file using GitHub. Does this update the PR automatically, or is there some other step I need to perform?

Thanks in advance.

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
I resolved the merge conflict (a style change in referencing the test name). @TerryGLee Could you review the PR again when you have a chance? Thanks.

**Review by TerryGLee — APPROVED** [review]

**Comment by TerryGLee** [comment]
#sign-off

**Pull request merged**
