### PR TITLE
Update toc.yml (Typo ".Suo"→".suo")

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-user-options-dot-suo-file?view=vs-2022
https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/extensibility/internals/toc.yml
related #7986 (Typo ".Suo"→".suo")
#PingMSFTDocs

### CODE REVIEW

**Comment by Court72** [comment]
@ghogen

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by TerryGLee** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@TerryGLee: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ghogen** [comment]
#sign-off

**Comment by PRMerger4** [comment]
@ghogen: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
