### PR TITLE
Update Platform option docs until we fix it

### PR DESCRIPTION
**Pull request by nohwnd**
Update platform option until we fix it, or decide to deprecate it. The option is hardly ever useful, and partially broken, and the docs should reflect it.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nohwnd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by nohwnd** [comment]
@pavelhorak updating the docs for platform. I am still researching how and if we should fix it, but the docs should reflect the real situation till then.

**Review by Mikejo5000 — APPROVED** [review]

**Comment by Mikejo5000** [comment]
@nohwnd Is this OK to merge?

**Comment by Mikejo5000** [comment]
#sign-off Assuming OK

**Comment by nohwnd** [comment]
@Mikejo5000 I was asleep, different timezone 🙂  but it was OK.

**Pull request merged**
