### PR TITLE
Fix typo in getting-started-with-devinit.md

### PR DESCRIPTION
**Pull request by aurichar**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@aurichar : Thanks for your contribution! The author(s) have been notified to review your proposed change. @andster

**Comment by gregvanl** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@gregvanl: I'm sorry - only the author of this article, @andster, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by andysterland** [comment]
I think I 
need to fix the owner metadata to be my github name not my MS alias..

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@andysterland I updated the metadata `author` value. Typically, changing metadata is initiated by the author or the content team in a PR in the private repo, but I've done this one. If you have other articles, you might open a PR to fix all of them.  Thanks!

**Pull request merged**
