### PR TITLE
Update walkthrough-manually-deploying-a-clickonce-application.md

### PR DESCRIPTION
**Pull request by AlexB-SheldonMFG**
#5664, Write-the-Docs-2020

### CODE REVIEW

**Comment by PRMerger17** [comment]
@AlexB-SheldonMFG : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
