### PR TITLE
Update warning descriptions and demo for C++ static analysis

### PR DESCRIPTION
**Pull request by Rastaban**
Update a few of the warning descriptions that were requested internally.  Tried to rephrase the descriptions to make them more useful to non-experts and improve the examples.

Also updated the demo project description to match VS2019 and better reflect the SAL best practices for annotations.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Rastaban : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mikeblome** [comment]
@jborsecnik approved for all commits. Thanks!

**Comment by Jak-MS** [comment]
hi @mikeblome and @Rastaban - in order to take advantage of the tools in the private repo (validation, staging, proofing, etc) we'll need to move the commits in this PR to the private repo (visualstudio-docs-pr) https://github.com/MicrosoftDocs/visualstudio-docs-pr 

Depending upon our bandwidth this may take a couple days, but we'll notify you when we're done, and @mikeblome will need to sign off on that new PR. 

thanks!

**Comment by Jak-MS** [comment]
new pr: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5915

**Comment by Rastaban** [comment]
I am unable to access https://github.com/MicrosoftDocs/visualstudio-docs-pr

**Comment by Jak-MS** [comment]
@Rastaban - yes, that's the private repository. Your changes were kept and merged into the repo from there. They should be live this afternoon. thanks!

**Comment by Jak-MS** [comment]
@Rastaban - if you're interested in working in the private repository in the future, that might be a possibility. Here's some information that might help:

> If you need help getting set up to work in the private repo, see [How to get to the private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master#how-to-get-to-the-private-repo). You can also take a look at the [GitHub account setup page](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master) for additional details on making sure you're set up.

**Pull request closed without merging**
