### PR TITLE
Update creating-a-windows-forms-toolbox-control.md

### PR DESCRIPTION
**Pull request by AlexB-SheldonMFG**
#5664, Write-the-Docs-2020

### CODE REVIEW

**Comment by PRMerger17** [comment]
@AlexB-SheldonMFG : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Looks good; merging.

**Comment by ghogen** [comment]
@ktoliver @AlexB-SheldonMFG Before merging this into the private repo, I checked and saw some problems.  There are places where "Select and hold" is used in the text, but it's not correct, the user has to double-click or double-tap.  In general, "select and hold" is the equivalent of right-click, not double-click.

**Comment by ktoliver** [comment]
Hi @ghogen I'll be happy to make a PR to fix things. The guidance doesn't address double-click, but it's clearly an action that requires a mouse. Is the equivalent on a phone or tablet selecting and holding, or is it double-tapping?

**Comment by ghogen** [comment]
@ktoliver Double tap is equivalent to double-lick - just tried it in Visual Studio for the scenario described in the article. Select and hold does something else - so for a button on a form, double-tap and double-click open the event handler in code.  Select and hold on the button brings up a menu.

**Comment by ktoliver** [comment]
@ghogen Ah, OK. Sorry for my edits. I'll create a PR in the private repo to fix it (change "double-click"/"double-clicking" to "double-tap"/"double-tapping", correct?). Are you happy with replacing "right-click" with "select and hold (or right-click)" per the guidance given for the Write-the-Docs effort? (Looks right to me, FWIW.)

**Comment by ghogen** [comment]
@ktoliver OK, tag me on the PR.  In some cases, we can use "open" or another verb instead of "double-click or double-tap" - that is more inclusive because keyboard actions also exist, usually selecting an item and hitting the Enter key, that are equivalent.

**Pull request merged**
