### PR TITLE
VS Subscriptions + GitHub is an offer

### PR DESCRIPTION
**Pull request by ItalyPaleAle**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ItalyPaleAle : Thanks for your contribution! The author(s) have been notified to review your proposed change. @evanwindom

**Comment by Jak-MS** [comment]
@gewarren - can you take a look?  github can't assign the article author(s) for some reason. thanks!

**Comment by ItalyPaleAle** [comment]
Thanks, please see my conversation over email @gewarren

**Comment by gewarren** [comment]
This will be live by 4:15 pm unless you need it live even sooner than that?

**Comment by ItalyPaleAle** [comment]
That's perfect, thanks for the quick turnaround!

**Comment by evanwindom** [comment]
I can’t approve anything where I’m listed as the author anyway, so thanks very much for your prompt help!

**Pull request merged**
