### PR TITLE
Added roslyn 4.5.0 and 4.6.0 to version support list.

### PR DESCRIPTION
**Pull request by AraHaan**

### CODE REVIEW

**Comment by AraHaan** [comment]
cc: @maiak

**Comment by Court72** [comment]
@maiak

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by maiak — APPROVED** [review]
#sign-off

**Comment by maiak** [comment]
#sign-off

**Pull request merged**
