### PR TITLE
fix: MD031/blanks-around-fences

### PR DESCRIPTION
**Pull request by nschonni**
Fenced code blocks should be surrounded by blank lines

### CODE REVIEW

**Comment by PRMerger13** [comment]
@nschonni : Thanks for your contribution! The author, @gregvanl, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're in the process of moving this commit to the private repo for validation and staging.

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @gregvanl, has been notified to review your proposed change.

**Comment by nschonni** [comment]
@ktoliver I know you're pulling this internally, but I fixed the conflict anyway

**Comment by ktoliver** [comment]
@nschonni @gregvanl Private repo PR 4471 replaces this pull request. We moved the commit to the private repo so we can validate formatting changes by using automated validation and staging. We'll close this PR now.

@nschonni Thanks for your contributions.

**Pull request closed without merging**
