### PR TITLE
chore: Remove sorted redirect

### PR DESCRIPTION
**Pull request by nschonni**
Believe this is just the result of https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/sort-redir.py, but isn't used unless the contents are actually put into the regular .openpublishing.redirection.json

### CODE REVIEW

**Comment by ktoliver** [comment]
@gewarren @ghogen Could you review the proposed changes? Thanks.

**Comment by gewarren** [comment]
Oops nice catch. I'll put these contents into .openpublishing.redirection.json.

**Comment by Jak-MS** [comment]
@gewarren - since you are going to move the contents (assuming that will occur in the private repo), can this PR be closed?  If not, can you provide specific guidance for this PR?

- `#sign-off` if it's ready to merge
- `#hold-off` if it requires changes before it's ready for sign off
- `#please-close` - if these changes aren't going to be merged

Thanks!

**Comment by nschonni** [comment]
If you pull it inside, it might be good to ignore the file in the .gitignore for next time

**Comment by gewarren** [comment]
Removing and adding the file to .gitignore in the private repo.

**Pull request closed without merging**
