### PR TITLE
Fix file names

### PR DESCRIPTION
**Pull request by NextTurn**

### CODE REVIEW

**Comment by GitHubber17** [comment]
@gewarren - If you approve the changes, we can move the commits to the private repo for proper testing. Thanks

**Comment by gewarren** [comment]
@Mikejo5000 This PR changes the name of a debugger topic - do you approve?

**Comment by Mikejo5000** [comment]
Looks like all the urls have been updated. This is actually a better filename for this topic, so it appears OK. Does the vs-2015 redirect look OK to you? I don't recall adding any for vs-2015. Thanks!

**Comment by Jak-MS** [comment]
@gewarren @Mikejo5000 - we'll move the commits in this PR to the private repo for validation, proofing, and staging checks. we'll tag you when it's ready.

**Comment by gewarren** [comment]
Closing this PR in favor of the private repo PR.

**Pull request closed without merging**
