### PR TITLE
Fix: Prematurely referring to "Greetings.xaml.cs"

### PR DESCRIPTION
**Pull request by Nightblade**
The file is still called "MainWindow.xaml.cs" at this point as we haven't renamed it yet.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Nightblade : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Review by anandmeg — APPROVED** [review]
Thank you for the updates.

**Comment by anandmeg** [comment]
#sign-off

**Pull request merged**
