### PR TITLE
Adding "Attach to a .NET Core process running on Azure App Service (Windows)" to the article "Attach to running processes with the Visual Studio debugger"

### PR DESCRIPTION
**Pull request by AngelosP**
Adding "Attach to a .NET Core process running on Azure App Service (Windows)" to the article "Attach to running processes with the Visual Studio debugger"

cc @timheuer, @MarcusFelling

### CODE REVIEW

**Comment by PRMerger8** [comment]
@AngelosP : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @AngelosP - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you. We'll close this pull request.

**Comment by AngelosP** [comment]
Hi @ktoliver,

> PMs should work in the private repo, per the Microsoft Docs contributor guide. 

Can you please point me to this private repo?

First click - no mention of a private repo:
image

Second click - no mention of a private repo:
image

Third click - no mention of a private repo:
image

The word "private" is not mentioned anywhere
image

When I search for internal repos, nothing comes up:
image


A search for other repos with the same name is not easy to diagest:
image

**Comment by ktoliver** [comment]
Hi @AngelosP I'll send you the information in an email. The contributor guide you quote is for the public-facing repository; the private repository is for Microsoft-internal contributors, and it's described in a Microsoft-internal contributor guide. Ideally, it would be part of the onboarding process for Microsoft employees. 

I can reopen this pull request for now, but we'll need to move the commit to the private repo to modify the image file to meet the internal style standards. 

@Mikejo5000 Do you have any guidance around the contents of the pull request or the private repo? 

Thanks.

**Comment by j-martens** [comment]
@AngelosP - Are you ready to sign-off?  Please open your PRs in our private repository going forward.

**Comment by ktoliver** [comment]
@j-martens There are blocking issues in the new image that's added here. That's why I suggested the private repo for this PR. For an external contributor, we would move the commit to the private repo and make the fixes. I sent them all the details and links in email. For simplicity, I'll go ahead and move the commit, so it can be resolved. I'll post here shortly and then will close this PR.

**Comment by ktoliver** [comment]
#sign-off for this PM-requested update @angelosP

**Comment by ktoliver** [comment]
We'll close this PR; the update will be merged in the private repo in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8340. Thanks.

**Pull request closed without merging**
