### PR TITLE
Fix repetitive phrasing in docs

### PR DESCRIPTION
**Pull request by bzier**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@bzier : Thanks for your contribution! The author, @kraigb, has been notified to review your proposed change.

**Comment by kraigb** [comment]
#sign-off

**Comment by kraigb** [comment]
For you, @gewarren

**Comment by gewarren** [comment]
@kraigb if you sign off on a PR in the public repo, like you did, the PR will get picked up for merging by the PR merge team. It's a manual process, but it does get done daily.

**Comment by kraigb** [comment]
@gewarren Thanks for clarifying the procedure. I haven't encountered it much before.

**Pull request merged**
