### PR TITLE
Add MSBuildWarnings(Not)As(Errors/Messages)

### PR DESCRIPTION
**Pull request by Forgind**
MSBuildWarningsAsMessages/Errors are already out. NotAsErrors should come out in 17.2.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Forgind : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ghogen** [comment]
@forgind
We probably shouldn't merge this until the feature becomes available, or else add a note that it's in 17.2

**Comment by Forgind** [comment]
Sounds good to me. Just let me know if there are changes you want in the interim.

**Review by ghogen — APPROVED** [review]

**Pull request merged**
