### PR TITLE
Fix bug with allowed symbols

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes dotnet/roslyn#47243

Needs review from Roslyn team.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Youssef1313 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sharwell** [comment]
⚠️ The original documentation was correct here.

**Comment by sharwell** [comment]
@ktoliver I don't have permissions to create a revert here. Can you revert this change?

**Comment by Youssef1313** [comment]
@sharwell I created a revert PR.

**Comment by ktoliver** [comment]
> @sharwell Sam Harwell FTE I created a revert PR.

Thanks @Youssef1313. The replacement PR is merged.

@sharwell Although there is a Revert button, the process it kicks off apparently is problematic, and we don't use it, the Microsoft Docs process to revert a merge is to create a replacement PR that contains the version you want to be live.

**Comment by ktoliver** [comment]
CC @ghogen

**Pull request merged**
