### PR TITLE
fix: MD046/code-block-style

### PR DESCRIPTION
**Pull request by nschonni**
Code block style

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@nschonni - Thanks for submitting these updates. We're in the process of moving the commit to the private repo, so we can verify the formatting on staging. We'll post a new PR # shortly and then close this PR.

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@Mikejo5000: I'm sorry - only the author of this article, @ghogen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
