### PR TITLE
Format the xml sample

### PR DESCRIPTION
**Pull request by meziantou**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@meziantou : Thanks for your contribution! The author, @gregvanl, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're in the process of pulling these commits to the private repo so we can verify the formatting changes on staging. We'll post a new PR # shortly and then close this PR.

**Comment by Jak-MS** [comment]
these commits are moved to the private repo for staging and validation: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/3642

**Comment by Jak-MS** [comment]
Thank you @meziantou! Your edits were reviewed and accepted. Your contribution is appreciated!

**Pull request closed without merging**
