### PR TITLE
Typo ".Sln"→".sln"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2022
https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/extensibility/internals/solution-dot-sln-file.md
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger5** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@leslierichardson95 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by TerryGLee — APPROVED** [review]

**Comment by PRMerger13** [comment]
@TerryGLee: I'm sorry - only the author of this article, @leslierichardson95, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by leslierichardson95** [comment]
#sign-off

**Pull request merged**
