### PR TITLE
Update walkthrough-creating-and-running-unit-tests-for-windows-store-…

### PR DESCRIPTION
**Pull request by scout208**
Updated to reflect VS2019.

Just updated a couple of names that have been changed in the VS2019 wizard. Someone should update the screenshots with the latest version. I don't know how the old ones were created to add the annotations so I didn't do it myself.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@scout208 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by gewarren** [comment]
@scout208 Is this change only applicable to VS 2019? If so, we'll need to add separate instructions for those two steps for VS 2017 and 2019 since the file applies to both. We can do that using moniker tags, e.g.:

::: moniker range="vs-2017"
instructions...
::: moniker-end
::: moniker range=">=vs-2019"
instructions...
::: moniker-end

**Comment by scout208** [comment]
@gewarren I'm not sure yet. I haven't tried it in VS2017 but I will take a look and update it accordingly.

**Comment by gewarren** [comment]
@scout208 Thanks for pointing out that these instructions weren't applicable to VS 2019. Since we share this page for VS 2017 too, I've added instructions for both versions in a PR in our private repo. I'm going to close this PR in favor of that one.

**Pull request closed without merging**
