### PR TITLE
Update tutorial-console-part-2.md

### PR DESCRIPTION
**Pull request by robinhood2014**
Added a note to notify the user on how to open the Autos window if it's hidden.

### CODE REVIEW

**Comment by Court72** [comment]
@anandmeg

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by robinhood2014** [comment]
Looks good. #sign-off

**Comment by anandmeg** [comment]
#sign-off

**Comment by anandmeg** [comment]
#sign-off

**Pull request merged**
