### PR TITLE
Update walkthrough-publishing-a-visual-studio-extension.md

### PR DESCRIPTION
**Pull request by SFC-Sarge**
d71051c4ba90ebc2e474efa403195bc1
5c502f08d95f52c8bdcb6bd2cf535862
7af89db1c55a910ccc0186276ee5d612
91b285e735c6ddd74a74363fa6b09ca4
d4f0607b1d72fe3daf7a78b2d36b42a4

Update a published extension in the Visual Studio Marketplace. I have the images but did not have rights to upload to the media folder.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@SFC-Sarge : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SFC-Sarge** [comment]
Did not mean to close

**Comment by leslierichardson95** [comment]
@TerryGLee can these pictures be added to the media folder before I sign off on this?

**Comment by SFC-Sarge** [comment]
Yes please.


Danny McNaught

Computer Question

Email: danny.mcnaught@dannymcnaught.com<mailto:danny.mcnaught@dannymcnaught.com>

Website: https://dannymcnaught.wixsite.com/website

Phone: 919-239-3306

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ktoliver** [comment]
Hi @SFC-Sarge @leslierichardson95 @TerryGLee - The new image files need to be moved to a different folder and renamed per 
the Microsoft file naming standard. Then, in turn, the image references in the MD file will need to be updated. To get things squared away before merging, the PR review team will move the updates approved in this pull request to the private repo. We'll merge from a new PR but the association with the original contributor will be intact. OK?

**Comment by ktoliver** [comment]
The new pull request has been created in the private repo. I've requested review from the content team. We'll close this pull request. Thanks!

**Comment by SFC-Sarge** [comment]
@ktoliver, I sent someone to the updated doc and they said the images did not show up in the document.  See picture below of document Red arrows point to missing images. I looked in the media folder and the ones you added are there but when I refresh the page. I still do not get the images. [walkthrough-publishing-a-visual-studio-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-publishing-a-visual-studio-extension.md)

Missing Images

**Comment by ktoliver** [comment]
Hi @SFC-Sarge You won't see the images render in [GitHub preview](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-publishing-a-visual-studio-extension.md), but you should see them on the [live docs.microsoft.com site](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension?view=vs-2019). Can you confirm the latter? I do see them on the live webpage myself.

The Markdown that's used here is preferred for creating Microsoft-internal image references. It does not render images in GitHub preview because it's custom Markdown. Content developers can view the images when they develop content in Visual Studio Code if they have the Docs Authoring Pack installed. The custom Markdown has many advantages, and the internal engineering team has recommended using it for internal content development.

**Comment by SFC-Sarge** [comment]
Yes, Thanks Kristine!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request closed without merging**
