### PR TITLE
clarify Time parameter per MicrosoftDocs/visualstudio-docs/issues/7066

### PR DESCRIPTION
**Pull request by WilliamAntonRohm**
MicrosoftDocs/visualstudio-docs/issues/7066

### CODE REVIEW

**Comment by PRMerger6** [comment]
@WilliamAntonRohm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@WilliamAntonRohm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
Hi @WilliamAntonRohm - This pull request was opened in the public repo. You can submit this type of update in the private repo and at-mention the article author if you'd like their review before signing off. Thanks.

**Pull request closed without merging**
