### PR TITLE
MSBuild: CLI switch -low

### PR DESCRIPTION
**Pull request by rainersigwald**
Copied from English help text.

### CODE REVIEW

**Review by paulomorgado — APPROVED** [review]

**Comment by Court72** [comment]
@ghogen

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]

**Comment by TylerMSFT** [comment]
Gordon is OOF for another week, so I reviewed/approved.
#sign-off

**Comment by TylerMSFT** [comment]
@Court72, Gordon is out for a week. I tried to approve this but am not the owner. Can you merge this?

**Comment by TylerMSFT** [comment]
@ShannonLeavitt - thank you :-)

**Pull request merged**
