### PR TITLE
Remove mention of ASP.NET 5

### PR DESCRIPTION
**Pull request by danroth27**
ASP.NET never really shipped as a supported platform. Long live .NET Core and soon .NET 5! :smile:

### CODE REVIEW

**Comment by PRMerger15** [comment]
@danroth27 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by LyalinDotCom** [comment]
Supporting this change too, its a good fix as ASP.NET is a working E&C scenario for code-behind

**Comment by ktoliver** [comment]
Hi @danroth27 - PMs should work in the private repository, per the contributor guide. We'll leave this PR here in the public repo for review, but would you submit future content updates in the private repo? Thanks!

**Review by Mikejo5000 — APPROVED** [review]
Thanks!

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by ktoliver** [comment]
There's an extra comma that should be deleted, but the PR isn't editable (`source: unknown repository`), so we'll merge. Maybe a tiny fix for a future update.

**Pull request merged**
