### PR TITLE
fix: MD031/blanks-around-fences

### PR DESCRIPTION
**Pull request by nschonni**
Fenced code blocks should be surrounded by blank lines.
Add code fence languages.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@nschonni : Thanks for your contribution! The author(s) have been notified to review your proposed change. @bytesguy

**Comment by Mikejo5000** [comment]
#sign-off Thanks!

**Comment by PRMerger8** [comment]
@Mikejo5000: I'm sorry - only the author of this article, @bytesguy, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change. @bytesguy

**Comment by ktoliver** [comment]
Resolved merge conflict.

**Comment by BytesGuy** [comment]
I no longer work for Microsoft so will defer this to @asb3993 Thanks

**Pull request merged**
