### PR TITLE
Update what-s-new-in-the-visual-studio-2017-sdk.md

### PR DESCRIPTION
**Pull request by wugelis**
英翻中 By Gelis at 2017/11/18.

### CODE REVIEW

**Comment by wugelis** [comment]
I Want to translated english to Chinese Taiwan.

**Comment by gregvanl** [comment]
Hi @wugelis, I don't understand the reason for this PR. Why do you want to translate the English version of the VS 2017 what's new to Chinese? Perhaps your PR is going against the wrong repository? 
Closing for now so that this PR won't be merged accidentally.

**Comment by wugelis** [comment]
Sorry

Because Microsoft open the translated Doc event for MVP(Microsoft Valuable Professional).

I should have to translate this zh-tw website correctly:
https://docs.microsoft.com/zh-tw/visualstudio/extensibility/what-s-new-in-the-visual-studio-2017-sdk

**Comment by gregvanl** [comment]
@nokura Do you have any guidance for @wugelis for helping translate the documentation on docs.microsoft.com.

**Pull request closed without merging**
