### PR TITLE
Update set-defaults-for-enterprise-deployments.md

### PR DESCRIPTION
**Pull request by edwardskrod**
The Installer enforces a 50 character limit for the CachePath.  Since we are improving discoverability of this registry setting, it makes sense to let admins know of this restriction so they don't inadvertently cause a breaking issue.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@edwardskrod : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@anandmeg

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ghogen** [comment]
Closing and reopening to trigger build validations.

**Review by anandmeg — APPROVED** [review]
Thanks for the updates!

**Comment by anandmeg** [comment]
#sign-off

**Pull request merged**
