### PR TITLE
Just updating to the latest Visual Studio folder under My Documents

### PR DESCRIPTION
**Pull request by yves-dolce**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@yves-dolce : Thanks for your contribution! The author, @mikejo5000, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@Mikejo5000 Can you take a look at this one?

**Comment by Mikejo5000** [comment]
@gewarren Taking a look

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
