### PR TITLE
Broken link fixed

### PR DESCRIPTION
**Pull request by mrcaron**
this link pointed to intro to C#, but it should point users to what's new docs.

Before creating your pull request, please check your content against these quality criteria:

### CODE REVIEW

**Comment by PRMerger18** [comment]
@mrcaron : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@mrcaron - thanks so much for catching this. @ghogen - please take a look.

**Comment by Jak-MS** [comment]
@mrcaron - take a look at the revision suggestion from @gewarren ... will you update your file and re-commit? after that I'll review it and we can merge the PR.

**Comment by mrcaron** [comment]
We're rolling out VS 2017 to our devs and I was just pretending to be a noob clicking through the docs :)

**Comment by Jak-MS** [comment]
@mrcaron - thank you!  @gewarren - can you sign off if you approve?

**Comment by PRMerger17** [comment]
@gewarren : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Pull request merged**
