### PR TITLE
Update visual-studio-commands.md

### PR DESCRIPTION
**Pull request by puya-ms**
Adds links to docs for better reading experience.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@TerryGLee - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TerryGLee — APPROVED** [review]

**Comment by TerryGLee** [comment]
#sign-off

**Comment by puya-ms** [comment]
@Jak-MS @TerryGLee Doesn't seem that worked.

**Comment by TerryGLee** [comment]
@puya-ms After this is merged, it'll get published within 24 hours.

**Comment by puya-ms** [comment]
Sorry @TerryGLee seems I was too impatient and thought the #sing-off didn't take affect since merge was still blocked. Never mind.

**Pull request merged**
