### PR TITLE
fixed 15.8 Preview 3 release info

### PR DESCRIPTION
**Pull request by PoulChapman**
also fixed naming on Preview releases

### CODE REVIEW

**Comment by PRMerger18** [comment]
@PoulChapman : Thanks for your contribution! The author, @TerryGLee, has been notified to review your proposed change.

**Comment by gewarren** [comment]
@TerryGLee Would you prefer if I closed this PR in favor of the private repo?

**Comment by TerryGLee** [comment]
Yes, please. I'll make note of the changes that Paul suggested and add them to the PR that I want to submit that includes today's releases. And, thanks for asking. :)

**Comment by gewarren** [comment]
@PoulChapman In the future please use the private repo because it creates less merge issues and you get a preview build. Terry will integrate your changes into her PR.

**Pull request closed without merging**
