### PR TITLE
Updating Docker URL to partnership URL

### PR DESCRIPTION
**Pull request by nebuk89**
Updating Hub URL to unique URL for Docker/MSFT experience 
cc @ghogen and @BigMorty

### CODE REVIEW

**Review by ghogen — APPROVED** [review]

**Comment by ghogen** [comment]
@nebuk89 Thanks for the update - can you explain this a little?  msftedge would seem to reference the Edge browser, but that doesn't make sense since users would be using any browser.

**Comment by ktoliver** [comment]
@ghogen This was overlooked in the pull request queue. Is the PR ready to merge? Thanks.

**Comment by ghogen** [comment]
@ktoliver I have pinged the requestor over email along with a product PM in Visual Studio tools.

**Comment by ktoliver** [comment]
@ghogen Thanks; we'll add #hold-off for now.

**Pull request merged**
