### PR TITLE
Remove redundant part of code

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Youssef1313 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TerryGLee** [comment]
#hold-off

**Comment by Youssef1313** [comment]
Well, from error msg it seems like Checked is nullable bool, not just bool.
My mistake, didn't test before opening pr.

**Comment by TerryGLee** [comment]
@Youssef1313 Although we weren't able to accept this PR, we do appreciate your taking the time to open one. We always appreciate when people want to help us improve our documentation.

**Pull request closed without merging**
